### ISSUE TITLE
Feat:Generate Reservation Confirmation Email Upon Successful Reservation Creation

### ISSUE THREAD

**Issue by 17arindam** [RamakrushnaBiswal/PlayCafe#101]
### Describe the feature

When a user successfully creates a reservation, the system should automatically generate and send a reservation confirmation email to the respective user's registered email address. 

### Add ScreenShots

![Screenshot 2024-10-06 155233](https://github.com/user-attachments/assets/adb16d7d-6a92-4c34-b798-d9b097ebeb7e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by 17arindam** [comment]
@RamakrushnaBiswal can you assign me this issue

**Comment by RamakrushnaBiswal** [comment]
@17arindam tell me what you are going to use

**Comment by 17arindam** [comment]
@RamakrushnaBiswal the selected reservation details will go to backend along with the user email .Then i will use nodemailer to generate a confirmation mail stating details of reservation and will send it to the that mail

**Comment by RamakrushnaBiswal** [comment]
Ok then go for it ⚡

**Comment by ekayZ7875** [comment]
Hello @RamakrushnaBiswal i would like to work upon this issue.Please assign it to me.

**Comment by RamakrushnaBiswal** [comment]
solved #121
