### ISSUE TITLE
Feat: Add Favicon to the website

### ISSUE THREAD

**Issue by hetvipopat** [RamakrushnaBiswal/PlayCafe#102]
### Describe the feature

I would like to add favicon as per the logo of website

kindly assign me this issue with appropriate labels

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@hetvipopat go for it ⚡

**Comment by Shiva-Bajpai** [comment]
@hetvipopat  have to added the fav icon ??

**Comment by AbrerAsif07** [comment]
PLs assign me to add the favicon to the site

**Comment by RamakrushnaBiswal** [comment]
solved via #134
