### ISSUE TITLE
Feat: want to add Login and signup pages with validation.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [RamakrushnaBiswal/PlayCafe#104]
### Describe the feature

This feature aims to implement user authentication functionality by creating dedicated login and signup pages within the application. The login page will allow existing users to access their accounts securely, while the signup page will enable new users to create accounts easily.

### Add ScreenShots

![Screenshot 2024-10-06 191316](https://github.com/user-attachments/assets/7133bf55-9dee-47e7-819f-5e9b57e283ec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@AbhijitMotekar99 actually we are using kinde auth and if login and signup pages needs i will assign you
