### ISSUE TITLE
Feat: Adding Perspective Hover Effect for Popular Board Games Card

### ISSUE THREAD

**Issue by AbhijitMotekar99** [RamakrushnaBiswal/PlayCafe#106]
### Describe the feature

This feature aims to enhance the visual appeal of the Popular Board Games card by implementing a perspective hover effect. This interactive design element will create an engaging user experience, making the cards more attractive and inviting.

### Add ScreenShots

![Screenshot 2024-10-06 191806](https://github.com/user-attachments/assets/77bbb0a3-b8ec-4833-bdd4-a6900d46d808)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@AbhijitMotekar99 go for it

**Comment by RamakrushnaBiswal** [comment]
colsed via #117
