### ISSUE TITLE
Feat: Want to add reserved successfully page which open after click on reserve now.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [RamakrushnaBiswal/PlayCafe#107]
### Describe the feature

This feature will implement a "Reserved Successfully" page that users will be redirected to after they click the "Reserve Now" button. This page will serve as a confirmation of their reservation, providing essential details and enhancing the user experience.

### Add ScreenShots

![Screenshot 2024-10-06 192053](https://github.com/user-attachments/assets/6fa5195b-4116-4110-935e-759ca94f64b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@AbhijitMotekar99 not needed
