### ISSUE TITLE
Feat: Adding Social media links with custom logo below feedback or contact us form.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [RamakrushnaBiswal/PlayCafe#108]
### Describe the feature

This feature will integrate social media links with custom logos positioned below the feedback or contact us form. This addition aims to enhance user engagement and provide alternative communication channels.

### Add ScreenShots

![Screenshot 2024-10-06 192503](https://github.com/user-attachments/assets/26d611ba-152b-4391-90c9-c70e317f8e76)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by Abhishek332** [comment]
Hi @AbhijitMotekar99 , Could I get this issue assigned with `hacktoberfest` label?
Could you please share which social media links you want to have it here

**Comment by RamakrushnaBiswal** [comment]
@Abhishek332 @AbhijitMotekar99 the social media links are in footer so need for now
