### ISSUE TITLE
BUG: Login Page is not there. I can create Login Page for the project. Please assign this issue to me.

### ISSUE THREAD

**Issue by isimarjitsingh** [RamakrushnaBiswal/PlayCafe#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Page is not available.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
hi @isimarjitsingh thank you for rising the issue actually we are using kinde auth for that so no need of login page
