### ISSUE TITLE
Feat: Adding Dark Mode Toggle that Automatically Adapts Website Content for a Seamless Experience

### ISSUE THREAD

**Issue by sumitkumar9128** [RamakrushnaBiswal/PlayCafe#112]
I’d love to see a dark mode toggle added to the site! It would be a great addition, especially for users who prefer darker themes or browse in low-light environments.

**What I’m Thinking:**

-There could be a toggle switch in the header  that lets users easily switch between light and dark modes.

-When dark mode is turned on, any content that’s currently in black (or other dark colors) would automatically switch to lighter colors (like white or light gray) to keep everything readable and looking good.

-I will make sure all text, buttons, icons, and other interactive elements still pop and are easy to interact with in both modes.

**Why This Would Be Awesome:**

-It’ll improve accessibility for users who prefer dark mode or browse at night.
-Plus, it’s a cool, modern feature that users expect from sites nowadays!

### Add ScreenShots

no

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by sumitkumar9128** [comment]
Kindly assign this issue to me with the appropriate label.
@RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
duplicate as #37

**Comment by sumitkumar9128** [comment]
Okay thanks for reply me
