### ISSUE TITLE
Feat: Homepage typer, PLAYCAFE, About us, feedback, and Footer is not Responsive for multiple devices

### ISSUE THREAD

**Issue by AliGates915** [RamakrushnaBiswal/PlayCafe#113]
### Describe the feature

**Description:** Several homepage sections are not properly responsive across different devices. The following areas need adjustments to ensure a consistent layout and functionality on mobile, tablet, and desktop screens:

**Typer (Animated Text):** The text overlaps or breaks on smaller screens. It needs better scaling or font adjustments.
**PLAYCAFE Section:** The content does not resize or align correctly on smaller devices, causing elements to stack improperly.
**About Us Section:** Text and images become misaligned on certain screen sizes, affecting readability and layout.
**Feedback Form:** Input fields and buttons are too cramped on mobile, making it hard for users to interact with the form.
**Footer:** The footer content overflows or gets cut off on smaller screens, requiring better spacing and layout adjustments.
@sanjay-kv  please assign this issue to me, if needed. 

### Add ScreenShots

![screencapture-play-cafe-vercel-app-2024-10-06-20_40_45](https://github.com/user-attachments/assets/e4dde357-b7e7-443f-b75d-41d714ff7fb0)
![screencapture-play-cafe-vercel-app-2024-10-06-20_39_08](https://github.com/user-attachments/assets/5f417215-1108-4d5e-b8e1-f360f82e0455)
![screencapture-play-cafe-vercel-app-2024-10-06-20_45_10](https://github.com/user-attachments/assets/85eca340-ed5d-45fd-853f-fcb2fc9b1f1a)
![Uploading screencapture-play-cafe-vercel-app-2024-10-06-20_44_29.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by AliGates915** [comment]
@RamakrushnaBiswal Assign this issue to me.

**Comment by RamakrushnaBiswal** [comment]
@AliGates915 i don't know which browser you used but me it works fine 
you can find other issues

**Comment by AliGates915** [comment]
I am using Chrome Browser. Ok but you again check @RamakrushnaBiswal I think it's not a fix.

**Comment by RamakrushnaBiswal** [comment]
I checked @AliGates915 
You can find another issues :)
