### ISSUE TITLE
Feat: Can improve the ui of testimonial card

### ISSUE THREAD

**Issue by iamsohelx** [RamakrushnaBiswal/PlayCafe#114]
### Describe the feature

Heyy @RamakrushnaBiswal In your website the testimonial cards are not looking good, we can improve the user experience by adding smooth transition and improving ui.

### Add ScreenShots

![cardplayCafe](https://github.com/user-attachments/assets/d3c0b210-1be9-476f-8ff2-542b2f0e6b0d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by iamsohelx** [comment]
Hey @RamakrushnaBiswal could you please assign this task to me, i can help you to improve the card ui making the user experience even smoother.
![improvedCafe](https://github.com/user-attachments/assets/40cdc026-8552-42be-84ab-dea6b1d66d32)
Similar to this or i can create as you wanted

**Comment by RamakrushnaBiswal** [comment]
duplicate #80
