### ISSUE TITLE
Feat:Adding logos with social media handles 

### ISSUE THREAD

**Issue by tanishirai** [RamakrushnaBiswal/PlayCafe#115]
### Describe the feature

Adding logos attract users and is easily accessible 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/af4e5989-55a5-4ab3-baea-cc4de82c68cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by tanishirai** [comment]
Also please add the label of gssoc-extd2024

**Comment by RamakrushnaBiswal** [comment]
Ok go for it @tanishirai
