### ISSUE TITLE
BUG: Landing page title words get split

### ISSUE THREAD

**Issue by AnanteshG** [RamakrushnaBiswal/PlayCafe#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The last letter of the last word in the Title of the landing page gets split into a new line. It is fine in laptop but my monitor is 22 inches and this problem arises.

Here's the image for ref :-
![{88C433F7-7690-4511-9B4C-BDF648409653}](https://github.com/user-attachments/assets/bc2d0522-9a55-42b1-b69b-5703ccaba75d)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by AliGates915** [comment]
yes, this is the bug @RamakrushnaBiswal assigned to me to fix it.

**Comment by AnanteshG** [comment]
Where?

**Comment by AliGates915** [comment]
> Where?

https://github.com/RamakrushnaBiswal/PlayCafe/issues/123#issue-2569287028

**Comment by AnanteshG** [comment]
> > Where?
> 
> https://github.com/RamakrushnaBiswal/PlayCafe/issues/123#issue-2569287028

Okay! Sorry for creating another issue.
