### ISSUE TITLE
BUG: Modified About us Page

### ISSUE THREAD

**Issue by ishakatiyar06** [RamakrushnaBiswal/PlayCafe#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

"Enhanced the 'About Us' section by making the text more visible and darker, increasing readability with improved font contrast and shadow effects against the background image. Fixed a layout issue where the 'Customer Feedback' heading and carousel content were overlapping by adding appropriate margins and padding, adjusting the review card heights, and repositioning navigation buttons for better responsiveness and clarity."
![Screenshot 2024-10-01 223742](https://github.com/user-attachments/assets/f5aa9316-ea5d-4e20-af25-0a8f4752bd5c)
Improved version
![Screenshot 2024-10-01 233016](https://github.com/user-attachments/assets/218f1a48-581c-4569-92e5-ca337d54fa0a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
I think it's not needed for now you can find another issues or what we need to add in our website
