### ISSUE TITLE
Feat:

### ISSUE THREAD

**Issue by hana-maria** [RamakrushnaBiswal/PlayCafe#122]
### Describe the feature

 Add some hover effects
1. Animations 
2. Short preview of the game( rules)

### Add ScreenShots

<img width="1039" alt="Screenshot 2024-10-07 at 7 38 59 AM" src="https://github.com/user-attachments/assets/9706c85f-86aa-459f-9167-bade3e4f234a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@hana-maria what you are going to do any idea ??
i mean any sample
