### ISSUE TITLE
BUG:  NavLinks are not show | Footer social media needed icons 

### ISSUE THREAD

**Issue by AliGates915** [RamakrushnaBiswal/PlayCafe#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

1. The navigation links (NavLinks) do not appear on the website. 
2. The footer is missing icons for social media links that must be added.
See video:  https://drive.google.com/file/d/1QULzIFbawFeZ7-34NBz_iXxzQfWHamPD/view?usp=sharing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by AliGates915** [comment]
@RamakrushnaBiswal please again review this issue, already told you last night, but you are closing my issue to tell me my side is everything is ok. Also please add the label of gsoc-extd2024 and assign me this issue.

**Comment by geetanjalidubey9** [comment]
can you pls assign this task to me

**Comment by RamakrushnaBiswal** [comment]
@AliGates915
make sure your screen size is set to be 100% 
i think you set it in 110% so you will get this error

![image](https://github.com/user-attachments/assets/d891c063-1c7c-4503-b4b1-05cb9b20c4af)

if any other issues let me know

**Comment by AliGates915** [comment]
I am working on it. When I am facing to another issue then tell you.

**Comment by AliGates915** [comment]
> I am working on it. When I am facing to another issue then tell you. @RamakrushnaBiswal

@RamakrushnaBiswal  see my PR https://github.com/RamakrushnaBiswal/PlayCafe/pull/149

**Comment by RamakrushnaBiswal** [comment]
hi @AliGates915 1st create issue then send PR

**Comment by AliGates915** [comment]
> hi @AliGates915 1st create issue then send PR

You already assign to me this issue.

**Comment by RamakrushnaBiswal** [comment]
@AliGates915 i am not

**Comment by RamakrushnaBiswal** [comment]
solved via #164
