### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by shreya-paul-17** [RamakrushnaBiswal/PlayCafe#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Dear Project Admin @RamakrushnaBiswal , 

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-extd contributor
- [ ] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by Shiva-Bajpai** [comment]
@shreya-paul-17 Sure we will take of the labels on issues & PRs

**Comment by RamakrushnaBiswal** [comment]
@shreya-paul-17 we are given appropriate level you can check in our repo and we didn't give `hacktobrfest-accepted` in level 2 and level 1 issues because it counts spam in hacktobr fest 
If it needed to add hacktobrfest-accpted tag in level 2 and level 1 issues 
Let me know

**Comment by shreya-paul-17** [comment]
@RamakrushnaBiswal just remember to give that hacktoberfest-accepted label to the quality contributions made in your project and not to the PRs with minor changes, README updates and so on

**Comment by RamakrushnaBiswal** [comment]
yh ok then @shreya-paul-17 we will take care of it 

can you please close the issue
