### ISSUE TITLE
Performance Optimization and Modularization Improvements

### ISSUE THREAD

**Issue by tejasbenibagde** [RamakrushnaBiswal/PlayCafe#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I identified several optimization and modularization issues that are causing the site to perform slowly.

Proposed Changes:

Refactor code for better modularization.
Optimize performance to enhance loading speeds and overall user experience.
This may involve changing multiple files across the project.
Next Steps: I would like to request to be assigned to this issue to implement the necessary changes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
assigned @tejasbenibagde
