### ISSUE TITLE
Upgrade Responsiveness of Website 

### ISSUE THREAD

**Issue by rajatsinghal02** [RamakrushnaBiswal/PlayCafe#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I want to update the Responsiveness of whole the website as it is not responsive in mobile verison
Please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@rajatsinghal02 not the whole website their are some parts are not responsive please attach some screenshots then we'll move further

**Comment by Shiva-Bajpai** [comment]
@rajatsinghal02 I am assigning this to you start to work on this issue and make it responsive in all versions

**Comment by RamakrushnaBiswal** [comment]
no work @rajatsinghal02 closed
