### ISSUE TITLE
Feat:A Modal Pop up before logout 

### ISSUE THREAD

**Issue by 17arindam** [RamakrushnaBiswal/PlayCafe#135]
### Describe the feature

currently when we click on logout it directly logs us out without any confirmation this way user can misclick on logout button and they have to login again . so i want to add a modal that will confirm to logout .

### Add ScreenShots

![image](https://github.com/user-attachments/assets/86527796-fe10-4a79-a722-25fc061711ed)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by 17arindam** [comment]
@RamakrushnaBiswal please assign me this issue

**Comment by RamakrushnaBiswal** [comment]
@17arindam use `antd`  UI for that.
Assigned

**Comment by RamakrushnaBiswal** [comment]
solved via #175
