### ISSUE TITLE
Feat:Store Newsletter Email and Send Thank You Email

### ISSUE THREAD

**Issue by 17arindam** [RamakrushnaBiswal/PlayCafe#136]
### Describe the feature

Implement functionality to store the email address of a user who subscribes to the newsletter in the database, and send a thank you email to the registered email address upon successful registration.

-Create an endpoint to accept the email address and store it in the database.
-After successful registration, trigger an email to the registered address.
-The email should thank the user for subscribing to the newsletter.

I will use nodemailer to send the mail to registered email 

### Add ScreenShots

![Screenshot 2024-10-08 051624](https://github.com/user-attachments/assets/aa588395-1a6a-404d-82bb-5084f018e7cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by 17arindam** [comment]
@RamakrushnaBiswal can you assign me this issue

**Comment by RamakrushnaBiswal** [comment]
@17arindam good idea you can work upon it

**Comment by RamakrushnaBiswal** [comment]
solved via #174
