### ISSUE TITLE
Feat: Navbar links do not scroll to the top of the page upon clicking, leading to incorrect initial view position.

### ISSUE THREAD

**Issue by Ashwinib26** [RamakrushnaBiswal/PlayCafe#138]
### Describe the feature

When clicking on navigation bar items, the website redirects to the correct page, but the scroll position remains at the previous page's level. This causes the content to be partially displayed, impacting user experience. Implementing automatic scrolling to the top when a new page loads can resolve this issue.

### Add ScreenShots

**This appears when user is on the lower section of menu page and clicks on reservation page (scroll position remains at the previous page's level) :**

![current view](https://github.com/user-attachments/assets/b48d4d68-3842-4bb7-a9e8-7f3dce4ceb72)

**It should actually be like (scroll position should be at the top on redirection) :** 

![improved view](https://github.com/user-attachments/assets/5630845c-656d-4d51-8c8b-dfb717114c84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Ashwinib26 go for it ⚡

**Comment by Ashwinib26** [comment]
Thank you @RamakrushnaBiswal for assigning the issue.

**Comment by RamakrushnaBiswal** [comment]
Solved via #215
