### ISSUE TITLE
Feat:Add hover effects and offer prices to items in Today's Special section of Menu page

### ISSUE THREAD

**Issue by Ashwinib26** [RamakrushnaBiswal/PlayCafe#139]
### Describe the feature

Enhancing the user experience by adding hover effects and displaying offer prices on items in the "**Today's Special**" section of the Menu page can be done. The hover effect should highlight the item, change the background,border, and show the offer price as a tooltip or overlay. This will attract user attention to special deals and improve visual appeal.

### Add ScreenShots

Improvement in this part : 

![items](https://github.com/user-attachments/assets/61c2d2ae-35ad-4348-ba3e-ad7e89582b61)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Go for it ⚡ 
@Ashwinib26

**Comment by Ashwinib26** [comment]
Thank you @RamakrushnaBiswal for assigning the issue.

**Comment by RamakrushnaBiswal** [comment]
colsed via #228
