### ISSUE TITLE
Feat: Addition of event details and improvement in UI of Events page 

### ISSUE THREAD

**Issue by Ashwinib26** [RamakrushnaBiswal/PlayCafe#140]
### Describe the feature

Enhancement in the Events page by adding separate sections for **Past Events, Upcoming Events, and Suggested Events** to better categorize event details and user involvement. Improvement in the overall UI by refining the layout, adding interactive elements, and using visually appealing styles. This will create a more organized and engaging user experience.

### Add ScreenShots

This page need to be improved by adding the above mentioned features and functionalities.

![events](https://github.com/user-attachments/assets/d814e8cd-af9b-4619-ada6-39f459fbc8cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Ashwinib26 no it looks good

**Comment by Ashwinib26** [comment]
@RamakrushnaBiswal I am try to say that if we'll add pictures of previous events held at the place , some upcoming events and suggestions from customer for new events would attract more customers and their involvements.
It looks good now as well , moreover these changes may enhance it even more , if you consider it , I could make those changes in the events part.
