### ISSUE TITLE
Feat: Set Up User Session Management

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#144]
### Describe the feature

Description
After setting up login functionality, it's essential to manage user sessions. This will ensure users remain authenticated across requests, allowing access to protected routes.

Acceptance Criteria:

Session Middleware:
Use express-session to handle session management.
Configure sessions to be stored securely (consider using a database like MongoDB for session storage).

Ensure User Authentication:
Middleware to check if a user is logged in before accessing certain routes (e.g., /profile or admin-only routes).
Redirect or return error if user is not authenticated.

Persistent Login:
Use cookies to maintain session across different requests.
Implement session expiration for security.

Tasks:
 Install and configure express-session.
 Create middleware to check if a user is authenticated.
 Set up session expiration and storage.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/330a5ec1-c5f3-49ad-8d89-7b9644b0a5f2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Assigned @samar12-rad

**Comment by Sourabh782** [comment]
hello @RamakrushnaBiswal, i see this issue is idle for about 3 weeks, if its free can i work on it?

**Comment by RamakrushnaBiswal** [comment]
ok @Sourabh782 go for it rise a PR asap coz gssoc-ext about to end

**Comment by Sourabh782** [comment]
> ok @Sourabh782 go for it rise a PR asap coz gssoc-ext about to end

Ya sure, started working on it, will make today only 👍👍
