### ISSUE TITLE
Password Reset funtionality For Users, (Frontend and Backend)

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#145]
### Describe the feature

Description
Allow users to reset their password in case they forget it. This will involve sending an email with a token that allows them to securely update their password.

Acceptance Criteria:
Request Password Reset (POST /api/request-password-reset):

Accept user’s email.
Generate a secure token using a library like crypto.
Send email with password reset link containing the token (use a service like SendGrid or Nodemailer).

Reset Password (POST /api/reset-password):
Validate the token.
Allow the user to set a new password.
Hash the new password using bcrypt.

Tasks:
 Create route to request a password reset.
 Generate token and send it to the user via email.
 Create route to reset the password with token validation.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/90ec78fa-1daa-49c3-b497-94b076c04c3b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad assigned

**Comment by samar12-rad** [comment]
Thank you @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
solved via #177
