### ISSUE TITLE
Feat: Add JWT-Based Authentication

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#146]
### Describe the feature

Description
To move towards a stateless authentication model, implement JSON Web Token (JWT) authentication instead of session-based authentication. This will allow frontend clients to handle the token and pass it with each request.

Acceptance Criteria:

Sign-Up and Login Return JWT:
After successful login or sign-up, return a JWT to the frontend.
The token should contain user details and role, with an expiration time.

Protect Routes with JWT:
Use jsonwebtoken to validate JWTs in protected routes.
Ensure secure token handling and error checking.

Logout by Invalidating JWT:
Implement token invalidation or simply remove the token from the client.

Tasks:
 Install and configure jsonwebtoken.
 Update login route to return JWT instead of using sessions.
 Add middleware to protect routes by verifying JWTs.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/8e880a55-055a-469d-bb3f-ad1dead855da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Assigned @samar12-rad

**Comment by samar12-rad** [comment]
Thanks @RamakrushnaBiswal
