### ISSUE TITLE
Implement OAuth Authentication with Passport.js

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#148]
### Describe the feature

Description
Integrate OAuth authentication into the application using Passport.js. This will allow users to log in using their existing accounts from social media platforms **Google** improving user experience and simplifying the sign-up process.

Acceptance Criteria:

Configure Passport.js OAuth Strategy:
Set up strategies for popular OAuth providers for **Sign in with Google**.
Ensure users can log in using their accounts from these providers.

User Account Management:
Create or link user accounts in the database upon successful authentication.
Store necessary user details (e.g., name, email, profile picture) after OAuth login.

OAuth Routes:
Implement the following routes:
Login with Provider (GET /auth/google / ): Redirect to the OAuth provider for user authentication.
Callback Route (GET /auth/google/callback / ): Handle the response from the provider, complete authentication, and redirect users to the application.

Technical Requirements:
Use passport-google-oauth20, or other necessary packages for OAuth.
Ensure that appropriate scopes are requested during OAuth login to gather necessary user information.
Handle error responses from OAuth providers gracefully.
Tasks:

 Install necessary packages for OAuth strategies (e.g., passport-google-oauth20).
 Configure Passport.js for OAuth strategies in passport-config.js.
 Implement routes for initiating OAuth login and handling callbacks.
 Create user accounts based on OAuth authentication results.
 Test the OAuth flow with different providers to ensure functionality.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/169197d9-acc0-4904-8e5c-15257204c205)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by tarunkumar2005** [comment]
@RamakrushnaBiswal If it is not solved then i can work on google oauth implementation assign this to me under gssoc 2024 ext and hacktoberfest
