### ISSUE TITLE
Feat:Back to top button 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RamakrushnaBiswal/PlayCafe#151]
### Describe the feature

On scrolling down there should be a scroll to top button which create good user experience

### Add ScreenShots

on the bottom right corner there should a button which is pointing to top

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by Shiva-Bajpai** [comment]
@Sawan-Kushwah go for it.

**Comment by RamakrushnaBiswal** [comment]
solved via #153
