### ISSUE TITLE
BUG: Recreation of boardgame section

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RamakrushnaBiswal/PlayCafe#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://github.com/user-attachments/assets/ce9cbf83-26fd-47b9-a507-567bac9c8338

As you can see here the images are not fit in the container and on hover it behaving laggy

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Sawan-Kushwah I think it looks good 
You can find another issues :)
