### ISSUE TITLE
BUG:Navbar does not reset scroll position when navigating between pages

### ISSUE THREAD

**Issue by bj-jiwrajka** [RamakrushnaBiswal/PlayCafe#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When navigating between pages using the navbar, the scroll position from the previous page is retained. For example, if a user scrolls to the bottom of one page and then navigates to a different page, the new page also opens at the bottom, rather than resetting to the top.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by bj-jiwrajka** [comment]
@RamakrushnaBiswal please assign this issue to me. I would like to fix this

**Comment by RamakrushnaBiswal** [comment]
Duplicate as #138
