### ISSUE TITLE
Feat: Add Dockerfile 

### ISSUE THREAD

**Issue by haseebzaki-07** [RamakrushnaBiswal/PlayCafe#155]
### Describe the feature

I want to add Dockerfile to the root of the project. 
A Dockerfile creates a containerized environment for applications, ensuring consistent deployment across different environments, simplifying scaling and isolation, and eliminating conflicts between dependencies and system configurations.

### Add ScreenShots

file example

![Screenshot 2024-10-08 160011](https://github.com/user-attachments/assets/91788d97-86ee-45a9-a9b3-a380d619aa71)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Go for it ⚡ 
@haseebzaki-07

**Comment by haseebzaki-07** [comment]
sure @RamakrushnaBiswal
