### ISSUE TITLE
Feat:Home page just has extra margin

### ISSUE THREAD

**Issue by Mohith1490** [RamakrushnaBiswal/PlayCafe#16]
### Add ScreenShots

![Screenshot_2024-10-02_07_35_44](https://github.com/user-attachments/assets/522aaec2-3153-4d5c-8ec8-cd702bc5c9d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Mohith1490 Assigned
