### ISSUE TITLE
Feat: Implement Dark Mode Theme switcher for Improved User Experience

### ISSUE THREAD

**Issue by RaiDevX8** [RamakrushnaBiswal/PlayCafe#160]
### Describe the feature

Adding dark mode will enhance user comfort and accessibility

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by Shiva-Bajpai** [comment]
Go for it

**Comment by RamakrushnaBiswal** [comment]
@RaiDevX8 duplicate as #37
