### ISSUE TITLE
the current feedback form is not working

### ISSUE THREAD

**Issue by AyushSharma72** [RamakrushnaBiswal/PlayCafe#161]
### Describe the feature

i want to add a api which lets user submit the feedback to your email  i will use nodemailer

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7caaf318-aa67-4258-b3d8-ff1b308aac8b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

please assign ths issue to me @RamakrushnaBiswal

**Comment by Shiva-Bajpai** [comment]
go for it @AyushSharma72

**Comment by RamakrushnaBiswal** [comment]
@AyushSharma72 @Shiva-Bajpai it working please you guys can check
