### ISSUE TITLE
Remove Kinde Authentication for Future Integration of Passport.js

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#170]
### Describe the feature

Description: The current implementation of Kinde authentication in the frontend is causing conflicts and preventing the successful integration of Passport.js. Additionally, this setup has led to CORS errors that are blocking the backend from functioning properly.

Tasks:
Remove all Kinde authentication-related code from the frontend.

Impact: This change is critical to ensure the proper functionality of the backend and to allow for the planned integration of Passport.js for authentication.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/739da17e-6b52-487e-ab99-80a602f158fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @samar12-rad

**Comment by RamakrushnaBiswal** [comment]
solved via #169
