### ISSUE TITLE
Create User Login and Signup Pages for Frontend

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#171]
### Describe the feature

As i created backend for the login and signup routes with authentication, I want to add frontend of that integrations to the project. I will folow good UI rules that match with the website.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2cab2e75-2654-4ce5-b04b-9373e6a0c8a2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad go for it

**Comment by RamakrushnaBiswal** [comment]
solved via #173
