### ISSUE TITLE
Feat: Improving the Navbar UI

### ISSUE THREAD

**Issue by NilanchalaPanda** [RamakrushnaBiswal/PlayCafe#172]
### Describe the feature

- The current UI of the Navbar is very monotonic and simple.
- It can made attractive according to the theme of the website.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d2360f89-51ff-4651-9adb-51883cb7f6b3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
any UI screenshots  please attach

**Comment by ByteBard18** [comment]
I would like to work on this issue... Please let me know. Will be great experience for me to enhance some of the UI :)

**Comment by NilanchalaPanda** [comment]
Somewhat like this will give the website more professional yet modern look.

![image](https://github.com/user-attachments/assets/38a6315b-e496-4519-80f9-ecc6ce720bcc)

**Comment by NilanchalaPanda** [comment]
Great @RamakrushnaBiswal, will starting working upon it.
