### ISSUE TITLE
Feat:Add Multilingual Support

### ISSUE THREAD

**Issue by 17arindam** [RamakrushnaBiswal/PlayCafe#176]
### Describe the feature

I would like to propose the integration of multilingual support into the project. This feature would allow users to switch between different languages, enhancing accessibility and improving the user experience for non-English speaking users.

Key Requirements:

Language Options: Add support for multiple languages (e.g., Spanish, French, German, etc.).
Language Switcher: Provide a simple interface (e.g., a dropdown or toggle) for users to switch languages easily.
Dynamic Content Translation: Ensure that all user-facing text (buttons, labels, messages, etc.) is translated dynamically based on the selected language.
Fallback Mechanism: Implement a fallback mechanism for untranslated text, defaulting to English when needed.
Localization: Use industry-standard localization libraries to manage translations efficiently (e.g., i18n, or a similar package).
Benefits:

Increased accessibility for a global audience.
Improved user engagement by offering content in users' preferred language.
Potential for expanding the user base to non-English speaking regions.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/56b10ab5-3594-434f-8b22-5bc0d89812b1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by 17arindam** [comment]
@RamakrushnaBiswal can you assign me this issue

**Comment by RamakrushnaBiswal** [comment]
@17arindam which place you are going to add it

**Comment by 17arindam** [comment]
@RamakrushnaBiswal at the footer of the website

**Comment by RamakrushnaBiswal** [comment]
yh ok i will :) @17arindam don't worry

**Comment by 17arindam** [comment]
@RamakrushnaBiswal thanksss
