### ISSUE TITLE
Feat: Enhance review section.

### ISSUE THREAD

**Issue by SurajSG23** [RamakrushnaBiswal/PlayCafe#178]
### Describe the feature

Hey, i would like to add a new feature to the review section.

![image](https://github.com/user-attachments/assets/82fdceaf-d654-4764-92c7-31768889462e)

Since the review cards are static , i would like to make it move from right to left dynamically (add animation).
This will enhance the UI of your website and it will avoid user to click manual to see the next review.
Please assign me this task under gssoc-exd and hacktober fest.Thank You

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
duplicate as #80
