### ISSUE TITLE
BUG: Image is not properly imported

### ISSUE THREAD

**Issue by Syed-Farazuddin** [RamakrushnaBiswal/PlayCafe#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Due to improper import of image the application was breaking

<img width="1209" alt="Screenshot 2024-10-02 at 10 36 36 AM" src="https://github.com/user-attachments/assets/33af67b2-4468-447c-8e88-716039e8493f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
It is solved ig Check PR #3
