### ISSUE TITLE
Feat: Adding FAQ section

### ISSUE THREAD

**Issue by Mandy1200** [RamakrushnaBiswal/PlayCafe#180]
### Describe the feature

I will add a FAQ section 

in which i would like to add , for reservations , menus , boardgames or related doubts of a user

*** You may also suggest some of the FAQ's

### Add ScreenShots

 A simple FAQ section under the about us card

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @Mandy1200

**Comment by RamakrushnaBiswal** [comment]
@Mandy1200 work status

**Comment by Mandy1200** [comment]
It's almost completed , I am fixing the UI for more attractive look

**Comment by sameer-soni** [comment]
@RamakrushnaBiswal looks like there's no update, can I get assigned? I'll create this feature today if assigned.
