### ISSUE TITLE
BUG: Alignment Issue 

### ISSUE THREAD

**Issue by Mandy1200** [RamakrushnaBiswal/PlayCafe#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Their is some alignment issues in the main body 

In this heading overflowing
![Screenshot (100)](https://github.com/user-attachments/assets/78699f5b-6651-4333-83a7-b2c9b063dc50)

text is going out of the card
![Screenshot (99)](https://github.com/user-attachments/assets/4f26801e-c5d1-4a24-bfcd-e0396c10b959)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
it not an issue please check your screen size 
![image](https://github.com/user-attachments/assets/fd7996ba-2159-40d0-aed9-d769712fba6c)
