### ISSUE TITLE
Improve signup ui

### ISSUE THREAD

**Issue by Aditijainnn** [RamakrushnaBiswal/PlayCafe#183]
### Describe the feature

![image](https://github.com/user-attachments/assets/35a5dda1-6cb2-4775-873c-d9815c2f4c97)
this login box doesn't have closing button so adding that

### Add ScreenShots

assign this to me under gssoc ext and hacktoberfest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Aditijainnn it looks good to me no need to change :)
