### ISSUE TITLE
Addition of different board game slides under Boardgames through slideshow

### ISSUE THREAD

**Issue by Shirisha-16** [RamakrushnaBiswal/PlayCafe#184]
Along with the following slide i want to add some slides through slide show with side ">" buttons and some transitions .
![Screenshot 2024-10-09 172841](https://github.com/user-attachments/assets/e2a19510-499a-4450-a374-51e2c2d6de33)
example:
![Screenshot 2024-10-09 173556](https://github.com/user-attachments/assets/9ff1e9d8-0152-41ad-8e93-97cf08dca642)
This enhances the ui of page and shows the collections of boardgames to users.
I want to work on this issue
@RamakrushnaBiswal  assign me this work with gssoc-ext,hacktoberfest-accepted and level according to this issue .

**Comment by RamakrushnaBiswal** [comment]
@Shirisha-16 go for it 
use splide.js to do that

**Comment by RamakrushnaBiswal** [comment]
solved via #233
