### ISSUE TITLE
BUG: unable to move to home page after registering .

### ISSUE THREAD

**Issue by Shirisha-16** [RamakrushnaBiswal/PlayCafe#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Screenshot 2024-10-09 172639](https://github.com/user-attachments/assets/f9d2a5c5-6e3e-4a2e-8fc6-4cfb8140294b)
After clicking on let's go button i am unable to move to home page .
I want to work on this issue
@RamakrushnaBiswal assign me this work with labels gssoc-ext,hacktoberfest-accepted and level according to the issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Shirisha-16 ok add it
`already have an account` _login_

**Comment by Shirisha-16** [comment]
please add the label hacktoberfest accepted as well

**Comment by RamakrushnaBiswal** [comment]
@Shirisha-16 its a small issue so i  can't add `hacktoberfest accepted` lebel 
instruction from gssoc team

**Comment by Shirisha-16** [comment]
I have completed this task under splide part only
![Screenshot 2024-10-12 144643](https://github.com/user-attachments/assets/eac54b2b-2bbf-4ec2-bf4a-8ebd5c7235db)

**Comment by RamakrushnaBiswal** [comment]
ok then i am closing the issue @Shirisha-16
