### ISSUE TITLE
Addition of page to register an event and working of button on submit

### ISSUE THREAD

**Issue by Shirisha-16** [RamakrushnaBiswal/PlayCafe#186]
Creating a  page for registering an event and working of button on clicking "Register Event"
![Screenshot 2024-10-09 172723](https://github.com/user-attachments/assets/385da565-6211-4871-be13-d7edfeaac4fc)
I want to work on this issue
@RamakrushnaBiswal please assign me this task with gssoc-ext, hacktoberfest-accepted and level according to issue

**Comment by RamakrushnaBiswal** [comment]
@Shirisha-16 not planned yet 
i will inform you incase of needed
