### ISSUE TITLE
Feat:Responsiveness in nav and body

### ISSUE THREAD

**Issue by Mansi07sharma** [RamakrushnaBiswal/PlayCafe#187]
### Describe the feature

this is not good looking everything are mess up.

@RamakrushnaBiswal 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/07ddde8d-098b-4c47-b003-40971cd6c0af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
duplicate as #172
