### ISSUE TITLE
Feat: Let's make the website responsive

### ISSUE THREAD

**Issue by Syed-Farazuddin** [RamakrushnaBiswal/PlayCafe#19]
### Describe the feature

The website is not responsive and it makes the user experience bad if used on different devices

### Add ScreenShots

<img width="643" alt="Screenshot 2024-10-02 at 10 41 44 AM" src="https://github.com/user-attachments/assets/65e6d4bd-c228-49d5-bacb-9205501ee486">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Already assigned to someone in issue #7 

@Syed-Farazuddin

**Comment by Syed-Farazuddin** [comment]
@RamakrushnaBiswal, there are many other pages **that are not responsive.**

<img width="871" alt="Screenshot 2024-10-02 at 11 11 46 AM" src="https://github.com/user-attachments/assets/478f89dc-2059-4702-9eec-eb6f29fdcb3d">

**Comment by RamakrushnaBiswal** [comment]
Ok then @Syed-Farazuddin go for it make all pages responsive except landing page coz it's already assigned

**Comment by Syed-Farazuddin** [comment]
@RamakrushnaBiswal  Working on it !!!

**Comment by RamakrushnaBiswal** [comment]
solved via #56
