### ISSUE TITLE
Feat : Implement Light/Dark theme toggle button functionality

### ISSUE THREAD

**Issue by rajgharat07** [RamakrushnaBiswal/PlayCafe#191]
### Describe the feature

- The Light/Dark theme toggle feature allows users to switch between two visual modes: a light theme, which uses brighter colors and a white background, and a dark theme, which uses darker colors and a black or dark background. This feature enhances user experience by accommodating different lighting conditions, reducing eye strain in low-light environments, and providing a customizable look and feel.

### Add ScreenShots

I am unable to add ss

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
some is already working upon it #37 
if he didn't rise the PR  i will assign you
