### ISSUE TITLE
Create Profile Page for users to see Reservations 

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#192]
### Describe the feature

As the Backend for sign in and sign up is done, we can move to create profile page for Users. 
On the profile page, Users  can see their upcomming resservations, and also create and cancel resserations. 
I will create Complete Frontend And Backend for it.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1b859ffd-0b4c-438c-9836-9c84d5937c57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @samar12-rad

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal can I take this issue??

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 go for it
