### ISSUE TITLE
Feat: Google OAuth adding

### ISSUE THREAD

**Issue by krishpathak** [RamakrushnaBiswal/PlayCafe#197]
### Describe the feature

The features allows the user to register/login with his/her registered email id.

### Add ScreenShots

no Screenshot

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
duplicate as #148
