### ISSUE TITLE
BUG: Redirect to Login and toast Notification

### ISSUE THREAD

**Issue by haseebzaki-07** [RamakrushnaBiswal/PlayCafe#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

After successfully registering a user should be redirected to the login page instead of redirected to the Home page. Also user should receive a toast notification instead of alerts after successfully registering.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by haseebzaki-07** [comment]
Sure @RamakrushnaBiswal

**Comment by haseebzaki-07** [comment]
Hey @RamakrushnaBiswal should I work on this issue

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 i think its already there
