### ISSUE TITLE
BUG: About.jsx relative path to "bgpic" needs to be fixed 

### ISSUE THREAD

**Issue by mishradev1** [RamakrushnaBiswal/PlayCafe#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

About.jsx is throwing an error because of wrong relative path 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@mishradev1 assigned ⚡

**Comment by RamakrushnaBiswal** [comment]
Merged #3  @mishradev1
