### ISSUE TITLE
Feat: Password toggle button

### ISSUE THREAD

**Issue by Sourabh782** [RamakrushnaBiswal/PlayCafe#202]
### Describe the feature

password toggling feature so that user can verify their entered password

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6aa42a80-5e8f-41db-9991-1f1c14ca2790)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @Sourabh782

**Comment by Sourabh782** [comment]
On it @RamakrushnaBiswal
