### ISSUE TITLE
Adding wrong GSSoC labels!

### ISSUE THREAD

**Issue by smog-root** [RamakrushnaBiswal/PlayCafe#203]
You are adding a wrong label for the GSSoC-ext.
The level labels should not contain any spaces in between!
@RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@smog-root but my PRs are counted in the leaderboard 
@sanjay-kv @MastanSayyad please review

**Comment by MastanSayyad** [comment]
@smog-root the labels are correct as said dashes are not allowed but spaces are. 

![IMG-20241010-WA0015.jpg](https://github.com/user-attachments/assets/2a6af4e3-cd4e-4af2-ac35-9530658716e9)

**Comment by RamakrushnaBiswal** [comment]
@MastanSayyad ok I will change it :)

**Comment by RamakrushnaBiswal** [comment]
@MastanSayyad is this correct one ?

**Comment by MastanSayyad** [comment]
@RamakrushnaBiswal Level labels are correct, just change gssoc ext label

`gssoc-ext`

**Comment by RamakrushnaBiswal** [comment]
@MastanSayyad now

**Comment by MastanSayyad** [comment]
@RamakrushnaBiswal perfect

**Comment by sanjay-kv** [comment]
@RamakrushnaBiswal @MastanSayyad He provided me access to the repo., so i fixed it

**Comment by smog-root** [comment]
You're repo is short listed for PA with wrong labeling.

https://docs.google.com/spreadsheets/u/0/d/1HogIA94g8XQnY1J2nfjFneUyuedxxO5TYAcYcbTBLhE/htmlview?pli=1

**Comment by smog-root** [comment]
Okay got it! 👍
