### ISSUE TITLE
Feat:Forgot Password 

### ISSUE THREAD

**Issue by 17arindam** [RamakrushnaBiswal/PlayCafe#207]
### Describe the feature

Description:
We need to implement a "Forgot Password" feature that allows users to reset their password via a registered email. When a user clicks on "Forgot Password," they should be prompted to enter their registered email. Upon submission, the system should send a password reset link to that email.

Acceptance Criteria:
Add a "Forgot Password" button on the login page.
Prompt the user to enter their registered email after clicking the button.
Validate the email to ensure it is registered with the system.
Send a password reset link to the registered email.
Ensure the link contains a secure, time-sensitive token.
Provide appropriate success and error messages for the user, such as:
Success: "A password reset link has been sent to your registered email."
Error: "This email is not registered with our system."
Redirect users to a page where they can set a new password after clicking the reset link.

### Add ScreenShots

![Screenshot 2024-10-10 180548](https://github.com/user-attachments/assets/c43eb669-351f-454d-89c8-bf6163d8e621)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@17arindam check #177
