### ISSUE TITLE
BUG: Navbar is not responsive on mobile version.

### ISSUE THREAD

**Issue by NilanchalaPanda** [RamakrushnaBiswal/PlayCafe#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
- The navbar is not responsive in mobile version.
- The content stays as per the dimension, but the Navbar is overflowing.

## Preview
![image](https://github.com/user-attachments/assets/8e41c52c-676d-4cc6-b60c-43f5909301a0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
go for it @NilanchalaPanda
