### ISSUE TITLE
BUG: Remove Existing Warnings 

### ISSUE THREAD

**Issue by Syed-Farazuddin** [RamakrushnaBiswal/PlayCafe#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

There are few Existing warnings 

<img width="982" alt="Screenshot 2024-10-02 at 11 08 14 AM" src="https://github.com/user-attachments/assets/070e1505-5f7e-434e-b2ba-fc2d8f8a7033">
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
Go for it @Syed-Farazuddin

**Comment by RamakrushnaBiswal** [comment]
solved #24
