### ISSUE TITLE
Create Admin Creation and Login Pages 

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#212]
### Describe the feature

As there is admin panel integrated to the website now, We need to create way for admin to login and Create a admin.
I will create Admin Creation and Login to PlayCafe as Admin completely. Frontend and Backend.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a6de6552-0cae-4017-bfdd-bc027e3a4eee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @samar12-rad

**Comment by RamakrushnaBiswal** [comment]
its is solved @samar12-rad ig

**Comment by samar12-rad** [comment]
It is a page for joining as admin, we can't currently log in as admin .

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad ok

**Comment by Sourabh782** [comment]
> @samar12-rad ok

hii @RamakrushnaBiswal, considering we have admin routes on backend,
![image](https://github.com/user-attachments/assets/98bddbe9-c6cd-4e78-ae83-fcb8523cef0a)

ig we can create admin login and signup pages, so if this issue's free, can i contribute to it?

**Comment by RamakrushnaBiswal** [comment]
@Sourabh782 yes go for it 
please rise a PR asap coz the program near to end

**Comment by Sourabh782** [comment]
> @Sourabh782 yes go for it please rise a PR asap coz the program near to end

Ya sure, I'll make pr till tomorrow on time 👍, and also maybe the deadline will increase till 10 nov saw on gssoc24/discussion/288
