### ISSUE TITLE
Overflown footer and arrow 

### ISSUE THREAD

**Issue by Sarthakkashyapp** [RamakrushnaBiswal/PlayCafe#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The footer and the arrow at the bottom of the site is overflowing and also the footer is stucked to the background it does now scroll with respect to the site.

![Screenshot_2024-10-11-08-39-59-70_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/aee11128-bfc0-438a-93aa-2caf539300f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
hi @Sarthakkashyapp 
actually it's the navbar problem #208
