### ISSUE TITLE
adding github icon in footer 

### ISSUE THREAD

**Issue by devxMani** [RamakrushnaBiswal/PlayCafe#216]
### Describe the feature

Adding github icon and link to the footer for direct navigation to the repo for contributors

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1972075c-4380-427a-b99c-d0c32646631d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@devxMani add the github and linkedin

**Comment by RamakrushnaBiswal** [comment]
solved via #223
