### ISSUE TITLE
IMGAGE LOADING TIME OPTIMIZATION

### ISSUE THREAD

**Issue by Amnyadav** [RamakrushnaBiswal/PlayCafe#217]
all images are loading at once whenever we refreshed or visit the website first time.
it takes longer time to load all the images.

what i can do?
i can add lazy loading which loads images which are in user viewport only which enhance overall user experience

@RamakrushnaBiswal can you assign me ?

**Comment by RamakrushnaBiswal** [comment]
@Amnyadav lazy loading is already applied

**Comment by Amnyadav** [comment]
![Screenshot 2024-10-11 120205](https://github.com/user-attachments/assets/1e22a14f-babc-40ba-8d22-ed6137a49aee)

like this many more images are there

**Comment by RamakrushnaBiswal** [comment]
ok @Amnyadav go for it

**Comment by Amnyadav** [comment]
@RamakrushnaBiswal  please add hacktoberfest label

**Comment by RamakrushnaBiswal** [comment]
solved #232
