### ISSUE TITLE
BUG: new page is starting with footer section in view

### ISSUE THREAD

**Issue by sameer-soni** [RamakrushnaBiswal/PlayCafe#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://github.com/user-attachments/assets/93fa3e8e-eb53-4107-81d4-82d1d89edde7

Expected behavior: when user change the page, the first section of page should be visible and page should get scrolled to top automatically.

Bug: when user is in footer section (bottom scrolled) and he changes the page from nav links, he gets redirected to that page but gets in the footer section. As you can see in the video, when changing the page when footer is visible, not getting scrolled to top, not a good user experience.
I would like to solve this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate as #215
