### ISSUE TITLE
BUG: In Menu page imported image is not visible

### ISSUE THREAD

**Issue by Syed-Farazuddin** [RamakrushnaBiswal/PlayCafe#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

<img width="871" alt="Screenshot 2024-10-02 at 11 12 47 AM" src="https://github.com/user-attachments/assets/a1b6dae0-0820-4300-bf74-d42026af86b6">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
Solved via #17
