### ISSUE TITLE
Feat: Adding a responsive password strength meter

### ISSUE THREAD

**Issue by PavanTeja2005** [RamakrushnaBiswal/PlayCafe#220]
### Describe the feature

The password meter enhances use experience.
Adding a meter which can also change color and displays password strength below the password field elevates user experience.

### Add ScreenShots

![Screenshot 2024-10-09 070324](https://github.com/user-attachments/assets/a40f3c0d-a152-47cb-b26d-5a481a0a0def)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Looks good ⚡ assigned @PavanTeja2005
