### ISSUE TITLE
Unnecessary Horizontal scroll

### ISSUE THREAD

**Issue by Amnyadav** [RamakrushnaBiswal/PlayCafe#221]
while minimizing the screen width a unnecessary horizontal scroll is there  which will made an bad  user experience.

in full screen width a very slight horizontal scroll is there which is negligble ,but yes it is there

this is the ss of what i am getting 
![Screenshot 2024-10-11 154852](https://github.com/user-attachments/assets/450c055e-4cee-40f3-adc3-a23ae2f8e337)
 
this is what everyone expected
![Screenshot 2024-10-11 154908](https://github.com/user-attachments/assets/5b26d4ea-9149-4757-995f-c9a731734a5a)

Note: these ss are taken after minimizing the width it is not seen in full width

@RamakrushnaBiswal  can you assign me this?

**Comment by RamakrushnaBiswal** [comment]
@Amnyadav it's navbar issue

**Comment by RamakrushnaBiswal** [comment]
got it @Amnyadav

**Comment by Amnyadav** [comment]
@RamakrushnaBiswal please add hactoberfest label

**Comment by Amnyadav** [comment]
@RamakrushnaBiswal why it is close?

**Comment by RamakrushnaBiswal** [comment]
solved via #224

**Comment by Amnyadav** [comment]
Okiii

**Comment by Amnyadav** [comment]
![Uploading Screenshot 2024-10-13 200744.png…]()
![Uploading Screenshot 2024-10-13 200728.png…]()

scenes from currently hosted website

**Comment by RamakrushnaBiswal** [comment]
@Amnyadav i didn't see that 
![image](https://github.com/user-attachments/assets/d6d1bcf5-ec7c-47de-89bb-f50d69d8f46b)
