### ISSUE TITLE
BUG: Improving Home part of webhsite

### ISSUE THREAD

**Issue by sanikamandale17** [RamakrushnaBiswal/PlayCafe#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/2298e47a-796b-4ca1-aa37-35bc0966d7e4)
  The home page header text ("A unique café experience") is splitting across multiple lines improperly, leading to readability issues. The text should be resized or adjusted to fit on the screen without breaking words across lines.
@RamakrushnaBiswal ,Sir plz assign this issue to me I want to work on it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate as #141
