### ISSUE TITLE
BUG: Improving footer section 

### ISSUE THREAD

**Issue by sanikamandale17** [RamakrushnaBiswal/PlayCafe#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/2d9cbe82-a333-4866-9189-d9064c8ec76f)

I want to Improve footer section of  the website. Plz assign this issue to me @RamakrushnaBiswal

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
not needed it looks good @sanikamandale17 you can find another issues
