### ISSUE TITLE
BUG:Simplify and Improve the Login Page Design

### ISSUE THREAD

**Issue by sanikamandale17** [RamakrushnaBiswal/PlayCafe#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Screenshot 2024-10-11 214322](https://github.com/user-attachments/assets/6a19fce5-2681-4fd1-a54d-c9022cc6341f)
Make the login page easier to use by improving the layout. Adjust the spacing between the header and input fields, align the text better, and add more space around the fields for a clean and comfortable look. Ensure the page looks good and works well on all screen sizes, without the background image covering important content. Plz sir, @RamakrushnaBiswal  assign this issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@sanikamandale17 buddy it looks good to me no need to change it 
you can checkout another issues
