### ISSUE TITLE
Feat: Implement Image Placeholder to Prevent Blank Screen During Loading

### ISSUE THREAD

**Issue by tejasbenibagde** [RamakrushnaBiswal/PlayCafe#23]
### Problem
Currently, when images are loading on the pages, users may experience a blank space or a blurry effect, which detracts from the overall user experience. This can be especially noticeable during navigation between pages.

### Suggested Solution
To enhance the user experience, I propose implementing an image loading placeholder similar to the behavior in Next.js. This would involve:
- Displaying a skeleton loader or a blurred placeholder image while the actual image is loading.
- Once the image is fully loaded, the placeholder would be replaced with the actual image.

### Benefits
- Improves visual consistency during image loading.
- Provides users with a smoother experience, reducing the perception of loading times.
- Helps prevent layout shifts that can occur when images load.

### Additional Context
Implementing a loading placeholder will ensure that users do not see a blank screen, creating a more polished and user-friendly interface.

### Related Issues
- (Link to any relevant issues if applicable)

### Add ScreenShots

![issue image](https://github.com/user-attachments/assets/802f033a-7e3b-46ec-887f-a9673397539d)

As you can see in the provided screen shot that a user will see the blank screen because the images are not yet loaded. this is not at all a good user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
You can add a loader for that 
Coffee 🍵 type of loader gif

**Comment by RamakrushnaBiswal** [comment]
Send some screenshot of loader

**Comment by tejasbenibagde** [comment]
I am not adding the loader. I'll be adding the placeholders similar to the ones provided by the nextjs.

**Comment by tejasbenibagde** [comment]
you can refer to this documentation page if you'd like to learn more about it https://nextjs.org/docs/pages/api-reference/components/image

**Comment by RamakrushnaBiswal** [comment]
I think loader is good for landing page and in reservation page you can that

**Comment by tejasbenibagde** [comment]
I can add the preloader in the website also the page transition similar to my old portfolio site https://tejas-benibagde.netlify.app/ if you want me to do this I can add a issue regarding this. Please let me know.

**Comment by RamakrushnaBiswal** [comment]
Do both I will give it level 2 
Preloader like coffee loading typo of

**Comment by tejasbenibagde** [comment]
ok for now I'm opening a issue for this

**Comment by tejasbenibagde** [comment]
Please merge my pending pr so that I can start working on the new one.

**Comment by RamakrushnaBiswal** [comment]
Bro my classes from 1:30 to 6:30 so I will review PRs at night 🥲

You can create a new branch and start working

**Comment by tejasbenibagde** [comment]
Bro I'm on a full time job and doing this with the office PC lol.

**Comment by RamakrushnaBiswal** [comment]
@tejasbenibagde hi did you work upon it :)

**Comment by tejasbenibagde** [comment]
Ah Yes I did start working on this one, the problem is that the page transitions are a little laggy. So I'm trying to fix this issue.

**Comment by RamakrushnaBiswal** [comment]
@tejasbenibagde ok

**Comment by RamakrushnaBiswal** [comment]
solved via #88
