### ISSUE TITLE
Feat:Preloader And Page Transition

### ISSUE THREAD

**Issue by itznayan** [RamakrushnaBiswal/PlayCafe#230]
### Describe the feature

Preloaders and page transitions are UI/UX techniques used to enhance the user experience by providing smooth transitions between different states or pages in an application, making the app feel more responsive and polished. Here's a breakdown of these features in the context of a React application:

### Add ScreenShots

Improved User Experience: Reduces perceived wait time by providing feedback and smooth transitions.
Polished UI: Makes the application feel more professional and responsive.
Visual Consistency: Maintains a cohesive feel when navigating through th

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it #25 
assigned @itznayan
