### ISSUE TITLE
Feat: Improve Header Section Design and Increase Logo Size

### ISSUE THREAD

**Issue by shashmitha46** [RamakrushnaBiswal/PlayCafe#231]
### Describe the feature

The header section could be enhanced for better user experience and aesthetics. Below are the proposed improvements:

**Increase Logo Size:** The current logo is a bit small and could be hard to notice. Increasing its size would make it more prominent and visually appealing.
**Header Alignment & Spacing:** The navigation items and login button could benefit from slight adjustments in spacing and alignment. Ensuring consistent spacing between elements will provide a cleaner, more polished look.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/58625d24-f5ce-4931-96bf-5020e6e25e19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
not required @shashmitha46
