### ISSUE TITLE
Enhancing the UI of Footer Section

### ISSUE THREAD

**Issue by rithvikreddybasani** [RamakrushnaBiswal/PlayCafe#234]
The Footer Section does not look good(no proper spacing ,not selecting correct font) 

![image](https://github.com/user-attachments/assets/8dffd6a3-ab27-4a3a-8ddb-09912fc2c629)

and there is unnecessary space below the footer

![image](https://github.com/user-attachments/assets/e4adc58f-927b-4aab-a6ab-faeaedbcdd78)

I can resolve this issue
@RamakrushnaBiswal  can you pls assign me this issue?

**Comment by RamakrushnaBiswal** [comment]
@rithvikreddybasani just remove the extraspace for all the devices
