### ISSUE TITLE
BUG: Able to select past date for reservation

### ISSUE THREAD

**Issue by lade6501** [RamakrushnaBiswal/PlayCafe#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently user is able to select past date while making reservation, will add condition so that user can only select current or future day's. 
<img width="1438" alt="Screenshot 2024-10-12 at 9 20 46 AM" src="https://github.com/user-attachments/assets/cb2c0a3d-513b-43ef-ad18-1f6e9f434ca6">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [x] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
go for it @lade6501

**Comment by shalini-bhandari** [comment]
@RamakrushnaBiswal kindly assign me this issue
