### ISSUE TITLE
Topic: Fixing README inaccuracy to improve ease of setup for contributors

### ISSUE THREAD

**Issue by pranavajith** [RamakrushnaBiswal/PlayCafe#238]
### Describe the types of topics you'd add in our Website

![image](https://github.com/user-attachments/assets/fe2d54e3-ed05-47a8-b244-56f7172de6ee)

This is the steps by which someone might decide to set up the website. It doesn't indicate that we must perform both actions in frontend and backend, and only then by running both of them individually can we locally deploy and develop the codebase. I wish to clarify this.

Please assign GSSoC'24 extd Tag and relevant levels, and assign it to me. Thanks in advance.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by RamakrushnaBiswal** [comment]
go for it @pranavajith

**Comment by pranavajith** [comment]
Thanks! On it.

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal he has not raised the PR yet can I work on it!
