### ISSUE TITLE
BUG: UI Correction : Overlap of "Scroll to Top" button with Footer

### ISSUE THREAD

**Issue by pranavajith** [RamakrushnaBiswal/PlayCafe#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/2a8450c7-1a3c-46ff-ab33-17412ea2e3b0)

While not the most complicated or urgent of changes, it notifies a very simple and noticable oversight in UI, which, as is seen generally, can easily put off users who wish to use a professional website.
I would like to fix this.

Please assign GSSoC'24 and other relevant tags, and assign it to me.

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a gssoc-24-extd contributor
- [x] I want to work on this issue
- [x] I check the issue doesn't exist

**Comment by pranavajith** [comment]
Updated.

**Comment by RamakrushnaBiswal** [comment]
its not required @pranavajith
