### ISSUE TITLE
BUG: Links in footer not redirecting to correct page

### ISSUE THREAD

**Issue by lade6501** [RamakrushnaBiswal/PlayCafe#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The [Events](https://play-cafe.vercel.app/event) does not redirects to `Events` page. Similarly [Reservation](https://play-cafe.vercel.app/register) gives `404` page. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@lade6501 ok add it
