### ISSUE TITLE
BUG: Link Correction - 404 Not Found in Footer

### ISSUE THREAD

**Issue by pranavajith** [RamakrushnaBiswal/PlayCafe#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/be641f98-c0da-4ea6-a125-d5797f663de8)
![image](https://github.com/user-attachments/assets/09344c01-dd22-43ac-b40e-f05614e956db)

The "Events" button in footer redirects to "/event" instead of "/events", leading to a 404 Not Found Error. I'd like to fix it, to ensure that the user experience is seamless, and any user who happens to explore it doesn't appear confused as to why it redirects to a non-existent page.

Also, the "Reservation"  link redirects to "/register" instead of "/reservation", leading to the same issue. 

Please assign GSSoC'24 and other relevant tags, and assign the issue to me. Thanks!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate as #241
