### ISSUE TITLE
BUG: Customer Reviews Section Being Unprofessional

### ISSUE THREAD

**Issue by pranavajith** [RamakrushnaBiswal/PlayCafe#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/87d9e9dd-0b86-4a45-beb2-01193738683e)
![image](https://github.com/user-attachments/assets/daa9f6c7-61f4-4204-b38e-51696b8deb11)

Upon reaching the end of the reviews, it shows empty spaces to the right for 2 spaces (this may be because there isn't enough reviews, which means we either add 2 more, or remove the last 2), but worse is that when clicking next, it shows an entire frame of no reviews, before clicking next to go to the beginning. This is not user friendly design, and must be enhanced ASAP! (Front facing bug)

Please assign GSSoC'24 and other related tags, and assign it to me. Would love to get my hands greasy by solving this issue!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate as #141
