### ISSUE TITLE
BUG: Glitchy / Non-smooth Movement of Today's specials

### ISSUE THREAD

**Issue by pranavajith** [RamakrushnaBiswal/PlayCafe#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/857bcfc0-46ee-4e1b-b246-379f56e2cd9c)
![image](https://github.com/user-attachments/assets/a4a54767-ffc3-4367-82f4-aa329f6825ca)

The "Today's Specials" section does not seem to respond smoothly when hovered. It leads to the footer being jerked back and forth over hovering and un-hovering. This leads to a fragmented user experience, especially ones who wish to explore the specials of the day. I wish to fix this.

Please assign GSSoC'24 extd and other related tags, and assign the issue to me. Thanks!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@pranavajith actually we are going to add new UI of the website so i can't assign the issues
