### ISSUE TITLE
BUG: Subscribing to Newsletter positioning

### ISSUE THREAD

**Issue by pranavajith** [RamakrushnaBiswal/PlayCafe#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Uploading image.png…]()

Subscribe to Newsletter Component shouldn't be in "Boardgames" section. It must be either at HomePage, About or atleast Events. Those who get to end of Boardgames component are those who casually browse the games. It is not ideal to expect only them to reach the newsletter section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
no needed @pranavajith
