### ISSUE TITLE
Feat: Implement Preloader and Page Transition Effects

### ISSUE THREAD

**Issue by tejasbenibagde** [RamakrushnaBiswal/PlayCafe#25]
### Issue Title
Implement Preloader and Page Transition Effects

### Issue Description

**Enhancement Aim:**
To improve user experience by adding a preloader and smooth page transitions, enhancing the overall performance and aesthetics of the application.

**Suggested Changes:**
- Implement a preloader that displays while the page content is loading.
- Add smooth transition effects between page navigations for visual continuity.
- Ensure the preloader is customizable (e.g., animation styles, colors).

**Example Page Transition**
- https://tejas-benibagde.netlify.app/

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@tejasbenibagde assigned
