### ISSUE TITLE
Feat : Adding Animated Preloader

### ISSUE THREAD

**Issue by AbhijitMotekar99** [RamakrushnaBiswal/PlayCafe#252]
### Describe the feature

The new feature is an animated preloader that would display while the website is loading its contents. The preloader would help enhance user experience by providing a smooth and visually appealing loading indicator before the main content of the site is fully rendered.

## Below one is sample

https://github.com/user-attachments/assets/07dbb438-31ac-4d9e-abfb-a23be09cc22c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
well but some one is already added a good one you can check
@AbhijitMotekar99
