### ISSUE TITLE
BUG: Feedback form is not sending response to the project admin mail.

### ISSUE THREAD

**Issue by VinayLodhi1712** [RamakrushnaBiswal/PlayCafe#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

 Feedback form is not sending response to the project admin mail. So i want to create api in backend and then using nodemailer to send the reponse to the project admin mail using fetch api and all.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
Hy @VinayLodhi1712 it already there , soem deployment issues is there we will look into it
