### ISSUE TITLE
Feat: to add dark and light mode toggle

### ISSUE THREAD

**Issue by sv410** [RamakrushnaBiswal/PlayCafe#255]
### Describe the feature

adding the dark and light mode toggle attracts the customer and can use according to there preference's 

### Add ScreenShots

![WhatsApp Image 2024-10-12 at 6 03 50 PM](https://github.com/user-attachments/assets/9737adf1-3387-44fc-9a84-b032ced72483)
![WhatsApp Image 2024-10-12 at 6 02 58 PM](https://github.com/user-attachments/assets/2bdc02dc-0831-47dd-ae6e-9d6339da197c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
#37 duplicate
