### ISSUE TITLE
Footer Navigation Links Not Working as Expected

### ISSUE THREAD

**Issue by harshucoder** [RamakrushnaBiswal/PlayCafe#257]
The navigation links in the footer are not functioning correctly due to mismatches between the defined routes in the router configuration and the links in the footer. Currently, only the About and Boardgame links work properly, while the other links lead to 404 errors.
### 
**Steps to Reproduce:**

1. Open the application.
2. Scroll down to the footer section.
3. Click on each of the links:

- Home
- Events
- Reservation
- Boardgame
- About

Observe that only **Home About**  and **Boardgame** links work, while the others lead to a **404 error page**.

https://github.com/user-attachments/assets/8658f940-0970-458f-ae3f-ebab049811e3

I would like to be assigned this issue to contribute under **Hacktoberfest** and **GSSoC-ext**. Fixing the footer navigation links is an important step towards improving the project, and I am eager to assist

**Comment by RamakrushnaBiswal** [comment]
#241 duplicate
