### ISSUE TITLE
BUG: FIXING LAYOUT OF FEEDBACK SECTION

### ISSUE THREAD

**Issue by anushkaa-dubey** [RamakrushnaBiswal/PlayCafe#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/70bfdaf7-c564-4223-aeb4-b42c025b77f1)
I want to arrange the icon with the text , it is overlapped right now.
Please assign this issue to me under gssoc and hacktoberfest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@anushkaa-dubey go for it

**Comment by anushkaa-dubey** [comment]
I am working on it, will update you with the PR tomorrow .
