### ISSUE TITLE
Feat: ADDING GSAP ANIMATION TO NAVBAR | GSSOC_EXT | LEVEL 3

### ISSUE THREAD

**Issue by Hamza1821** [RamakrushnaBiswal/PlayCafe#261]
### Describe the feature

i wan to add smooth animation to navbar when the website is loaded for the first time

please assign this to me

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Hamza1821 Which type of any example

**Comment by Hamza1821** [comment]
I am talking about some sliding down animation to navbar with stagger effect

**Comment by RamakrushnaBiswal** [comment]
actually we are going to implement our new UI so nor need for now
