### ISSUE TITLE
Feat: Custom Toast Errors while form validation

### ISSUE THREAD

**Issue by tarunkumar2005** [RamakrushnaBiswal/PlayCafe#262]
### Describe the feature

Custom Toast Errors while form validation

@RamakrushnaBiswal Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c6269635-db44-40d1-b213-bf0cd478ee68)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
not needed @tarunkumar2005  for now
