### ISSUE TITLE
Feat: Addition of OTP based forgot password functionality (Frontend + backend)

### ISSUE THREAD

**Issue by Sourabh782** [RamakrushnaBiswal/PlayCafe#263]
### Describe the feature

Currently the site have no functionality if an user forgets his password, this feature is a must while creating a site with user authentication. This will add a forgot password functionality, where the user will receive an otp on his email to reset his password

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b63a28b3-60c2-4870-a0aa-b991974ca92e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Sourabh782 go fot it

**Comment by Sourabh782** [comment]
@RamakrushnaBiswal sure, on it 👍
