### ISSUE TITLE
BUG:Remove horizontal scrolling 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RamakrushnaBiswal/PlayCafe#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

As this create a bad user experience
Please assign me i can do it for all pages
![Screenshot_20241013_004201](https://github.com/user-attachments/assets/1663f7e5-0b1e-4d1c-82e3-ac75ee0288ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate @Sawan-Kushwah #208
