### ISSUE TITLE
BUG:login signup page is not working 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RamakrushnaBiswal/PlayCafe#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I can make them work with funcanility of signup with Google and custom email

Please assign me i can do this as I have done this work previously 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Sawan-Kushwah thank you for creating the issue it working but in deployment its not working we will fix that
