### ISSUE TITLE
BUG:boardgame page is not responsive 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RamakrushnaBiswal/PlayCafe#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![Screenshot_20241013_004656](https://github.com/user-attachments/assets/52bd6495-090d-481f-aea4-d792483fe345)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
suplicate as #208
