### ISSUE TITLE
Feat: Remove Branding and Logo of the google translate functionality to improve the user experience in the footer

### ISSUE THREAD

**Issue by rebornstar1** [RamakrushnaBiswal/PlayCafe#268]
### Describe the feature

This feature will hide the default Google Translate branding and logo that appear when integrating the Google Translate widget into the website footer. By removing these elements, the focus shifts entirely to the site’s content, resulting in a cleaner and more cohesive user interface. It enhances the overall user experience by maintaining a consistent design language throughout the site, especially in the footer section, where a clutter-free, professional look is important. This feature ensures that language translation remains seamless without distracting visual elements.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5ef48ce7-6bb9-4116-8691-9adddbd5b81e)
This looks extermely unprofessional

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@rebornstar1 no its required :)
