### ISSUE TITLE
BUG: fixing mobile responsiveness 

### ISSUE THREAD

**Issue by Sourabh782** [RamakrushnaBiswal/PlayCafe#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently there's problem with mobile responsiveness 

![Screenshot_20241013_072335_Chrome](https://github.com/user-attachments/assets/3ff72102-7218-473f-8f63-451b138f6dcd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate as #208
