### ISSUE TITLE
Feat: modern sticky footer

### ISSUE THREAD

**Issue by itznayan** [RamakrushnaBiswal/PlayCafe#27]
### Describe the feature

i wanna add modern sticky footer to the website which look like below video i will adjust it to match theme of website

https://drive.google.com/file/d/1M41a2-S1irR3a_Uizc4a5GPOf9SgMusV/view?usp=drive_link

### Add ScreenShots

https://github.com/user-attachments/assets/865ef495-2988-4fd3-822b-d7c44f107818

adding modern footer to website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
i didn't understand properly @itznayan

**Comment by itznayan** [comment]
> i didn't understand properly @itznayan


https://github.com/user-attachments/assets/44c8bbba-7dd0-4c6a-b405-6b0f741b87b0

**Comment by itznayan** [comment]
@RamakrushnaBiswal please approve PR i have sent pr request .

**Comment by RamakrushnaBiswal** [comment]
wait let me review it

**Comment by RamakrushnaBiswal** [comment]
it looks good to me,Thank you :) @itznayan

**Comment by RamakrushnaBiswal** [comment]
solved #38
