### ISSUE TITLE
Feat:  Newsletter Subscription Form for Website Footer

### ISSUE THREAD

**Issue by 09viv** [RamakrushnaBiswal/PlayCafe#270]
### Description:
A responsive and user-friendly newsletter subscription form designed for the footer section of a website, built with React and styled using Tailwind CSS. It allows users to enter their email to subscribe, with smooth interactions and customizable success messages.

Key Features:
Responsive Design for all devices.
Styled with Tailwind CSS for modern UI/UX

### Add ScreenShots

![Screenshot 2024-10-13 112616](https://github.com/user-attachments/assets/6cbece9c-fcc6-4ea7-8935-44726f2314ab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
its already there please check the website @09viv
