### ISSUE TITLE
Feat: Lack of Redux or State Management is Making Data Flow Hard to Manage

### ISSUE THREAD

**Issue by tejasbenibagde** [RamakrushnaBiswal/PlayCafe#271]
### Describe the feature

Right now, the app doesn't use any global state management like **Redux** or **Redux Toolkit**, which is causing some serious challenges. Each component is handling its own state independently, which makes managing data across the app messy and inconsistent. This approach works for small apps, but as this project grows, it’s going to become harder to keep everything in sync.

By adding **Redux** or **Redux Toolkit**, we could manage the state centrally, making the data flow smoother and reducing the duplication of logic. Plus, it will make the app much easier to maintain and scale in the long run.

However, adding Redux at this point will require a lot of work. It’s not just about setting up Redux, but also refactoring how the state is currently managed across the app, updating components, and testing everything to make sure nothing breaks. It’s a big job, but it will be worth it for the stability and scalability of the project.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@tejasbenibagde its a small web app so i don't think its required
