### ISSUE TITLE
UPDATION IN README FILE REQUIRED 

### ISSUE THREAD

**Issue by soham0028** [RamakrushnaBiswal/PlayCafe#274]
### Describe the feature

Hello @RamakrushnaBiswal 
the current readme file lacks proper structure and does not contain alot of things that are imp

1. Table of content for easy access 
2. back to top button for easy acccess
3. contributors section 
4. forkers and stargazers section 
5. featured in section 

Kindly Assign me the issue under hacktoberfest and gssoc-extd labels so my work is counted for these events 

### Add ScreenShots

will add for pr

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@soham0028 not needed
