### ISSUE TITLE
Feat: To add the Reservation page

### ISSUE THREAD

**Issue by Jay-1409** [RamakrushnaBiswal/PlayCafe#275]
### Describe the feature

I noticed that the Reservation page does not exist. 
The page description would be: 

- Choose Your Date and Time:
- Group Size Options
- Special Requests
- Contact Information

### Add ScreenShots

The UI/UX  will remain in theme with the other pages
My previous work : #129 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Jay-1409 
![image](https://github.com/user-attachments/assets/5a3cca2b-1072-44ff-b4bc-20d284f2eca5)
its there
