### ISSUE TITLE
Topic: Add "Remember Me" checkbox to the login form

### ISSUE THREAD

**Issue by Mrinmayee01** [RamakrushnaBiswal/PlayCafe#276]
### Describe the types of topics you'd add in our Website

Hi @RamakrushnaBiswal 
 
Description: This pull request adds a Remember Me" checkbox
to the login form. When users select this option,
their login credentials will be remembered for
future visits, allowing them to remain logged in for
a longer period. This feature will improve the user
experience by providing convenience, especially
for frequent users who prefer not to re-enter their
login details every time.

The feature includes:
A "Remember Me" checkbox in the login form.
Improved user convenience by allowing automatic
login without re-entering credentials for returning
users.

Please assign me this issue under GSSOC and Hacktoberfest.

### Could you share some screenshots or a video of your previous work?

![Screenshot 2024-10-13 202938](https://github.com/user-attachments/assets/7528488a-35d8-4e5d-9dd2-22b7b242d95f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by RamakrushnaBiswal** [comment]
@Mrinmayee01 well go for it

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal can I work on this issue??

**Comment by RamakrushnaBiswal** [comment]
go for it @haseebzaki-07
