### ISSUE TITLE
BUG: The Gif in the Events page is not Responsive.

### ISSUE THREAD

**Issue by NilanchalaPanda** [RamakrushnaBiswal/PlayCafe#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
- The Gif in the Events page is not Responsive.
- On larger screen, it looks perfect, but on mobile device the size is reduced and overlaps the text.

## Preview 
![image](https://github.com/user-attachments/assets/64ddd3e9-8cce-4220-8ce4-c7d1eefd1784)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
go for it @NilanchalaPanda

**Comment by NilanchalaPanda** [comment]
Great 🙌🏻
Can you also add `hacktoberfest-accepted` label. As I am participating in Hacktoberfest as well.
