### ISSUE TITLE
BUG: Text & Animation overlapping

### ISSUE THREAD

**Issue by Picodes10** [RamakrushnaBiswal/PlayCafe#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The tagline and animation overlap in the desktop view's feedback section.

![Screenshot 2024-10-13 233656](https://github.com/user-attachments/assets/2c6f806d-33fa-4179-996d-f92693c036a0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Picodes10 assigned
