### ISSUE TITLE
BUG: menu not closed automatically after clicking

### ISSUE THREAD

**Issue by Amnyadav** [RamakrushnaBiswal/PlayCafe#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in small sized screen whenever i clicked on particular tab it will lead me to that page but the menu remains open .i have to close it automatically. which is not providing a good user experience.

below is the ss
![Screenshot 2024-10-14 181118](https://github.com/user-attachments/assets/03a3f9b5-df3d-4bc2-8858-34a259dfdad6)

in ss you see i clicked on boardgames , but it remains open even after i reached that page.
@RamakrushnaBiswal  assign me this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by Shiva-Bajpai** [comment]
@Amnyadav go for it. There is a problem with the menu

**Comment by Amnyadav** [comment]
@Shiva-Bajpai  please add hacktoberfest label

**Comment by Amnyadav** [comment]
@RamakrushnaBiswal hey that horizontal scroll problem not solved yet .
i uploaded some ss from current hosted web
you can see one here

![Screenshot 2024-10-14 175225](https://github.com/user-attachments/assets/c819189e-557d-49b0-a020-597900b0c7e9)

**Comment by RamakrushnaBiswal** [comment]
@Amnyadav for ne it  solved , i mean it works fine in my browser

**Comment by RamakrushnaBiswal** [comment]
solve via #286
