### ISSUE TITLE
Topic: Rearrange the structure of the README 

### ISSUE THREAD

**Issue by alo7lika** [RamakrushnaBiswal/PlayCafe#285]
### Describe the types of topics you'd add in our Website

For a better understanding and attractive README, the structuring of the README is necessary

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by alo7lika** [comment]
ADD GSSOC EXT 24 AND HACKTOBERFEST LABELS. AND ASSIGN ME THIS WORK

**Comment by RamakrushnaBiswal** [comment]
well go for it, if your updated readme look good for me then only i will merge

**Comment by RamakrushnaBiswal** [comment]
solved via #294
