### ISSUE TITLE
Feat: Contact us page improve

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [RamakrushnaBiswal/PlayCafe#29]
### Describe the feature

the current contact us page is good but i feel i can improve it.

### Add ScreenShots

<img width="783" alt="Screenshot 2024-10-02 at 3 01 04 PM" src="https://github.com/user-attachments/assets/7cd9397f-3899-4904-a91a-c351b731a106">

I can rework on this section and fix the UI to make it a little better. can u please assign me this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@T-Rahul-prabhu-38 attach some UI screenshots.
