### ISSUE TITLE
BUG: Password strength visible before typing in Register page

### ISSUE THREAD

**Issue by lade6501** [RamakrushnaBiswal/PlayCafe#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Password Strength is visible even before user start to type password or any other fields which not a good user experience.
Should only show it when user starts typing password.

<img width="670" alt="Screenshot 2024-10-15 at 8 13 22 AM" src="https://github.com/user-attachments/assets/fad18da7-8a8e-4f29-bef6-73bfe87b9ea1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
its good btw otherwise ppl are going to direct submit the button @lade6501
