### ISSUE TITLE
Feat:Create sign up and login for responsible mobile app

### ISSUE THREAD

**Issue by Aditya90456** [RamakrushnaBiswal/PlayCafe#295]
### Describe the feature

make responsible sign up and login for mobile 

### Add ScreenShots

![BoardGame Cafe and 5 more pages - Personal 2 - Microsoft​ Edge Beta 10_15_2024 12_37_57 PM](https://github.com/user-attachments/assets/84f4cb0f-2a2a-40d6-855e-b31087323a10)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [ ] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Assigned @Aditya90456

**Comment by Aditya90456** [comment]
thank you
