### ISSUE TITLE
Feat: Lets add a memebership program to this website

### ISSUE THREAD

**Issue by Jay-1409** [RamakrushnaBiswal/PlayCafe#296]
### Describe the feature

The customer can buy this member ship and get benifits.
We can create a page which has this feature and we will have 2 -3 different membership programs
- Foods + games
- Games only

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Jay-1409 tell me more about the feature

**Comment by Jay-1409** [comment]
Sure !! @RamakrushnaBiswal 

-Feature Description:

The Membership Page will offer three different membership programs, each providing unique benefits:

-Foods + Games Membership:

Access to both the food menu and gaming lounge.
Special discounts on selected food items.
Free gaming credits each month.
Exclusive access to members-only events.

- Games Only Membership:

Unlimited access to all games.
Free gaming credits every week.
Invitations to members-only gaming tournaments.
Customizable Add-ons:

Customers can choose to add special perks like:
Free food on game days.
Extra gaming time.
Birthday party discounts.
Design Elements:
Clean and Visual Layout: Each membership plan will be displayed as a separate card or panel, with key features listed clearly.
Call-to-Action Buttons: Each card will have a "Sign Up" button to encourage quick membership sign-up.

**Comment by RamakrushnaBiswal** [comment]
go for it @Jay-1409

**Comment by Jay-1409** [comment]
Ok on it!!
