### ISSUE TITLE
Feat: Implement User Verification System with OTP for Email

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#297]
### Describe the feature

Description: We need to implement a user verification system to prevent spam user creation by sending a one-time password (OTP) to the user's email during the registration process. This will ensure that only verified users can access and use the system.

Requirements:

On user registration, generate a unique OTP and send it to the provided email address.
Create a new endpoint on the backend to verify the OTP.
Ensure the user cannot proceed to login or book events without successful OTP verification.
Set an expiration time for the OTP (e.g., 5 minutes).
Notify the user in case the OTP expires or if they enter an incorrect OTP.
Frontend: Create a verification page/form where users can enter their OTP.
Add error handling for scenarios like incorrect OTP, expired OTP, or network issues.
Tech Stack:

Backend: Express.js, Nodemailer 
Frontend: React (for the verification form)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1f638820-32f4-43ab-abd6-d9085792ea65)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @samar12-rad

**Comment by haseebzaki-07** [comment]
Hey @RamakrushnaBiswal he has not yet raised the PR , can I work on the issue

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 yes you can
