### ISSUE TITLE
Feat: Restrict Event Booking to Verified Users

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#298]
### Describe the feature

Description: Currently, the event booking page allows all users to access the "Book Now" feature. To enhance security and improve the user experience, only logged-in or verified users should be able to book new events. Non-authenticated users should be redirected to the login page if they attempt to book an event.

Acceptance Criteria:
Users who are not logged in should not be able to access the event booking functionality.
If a non-logged-in user clicks "Book Now," they should be redirected to the login page with a message prompting them to log in.
Logged-in users who have verified their email (or passed other verification criteria) can book new events.
Backend should verify the user's authentication and verification status before processing the booking request.

Tasks:
 Implement authentication check in the frontend to disable "Book Now" for non-authenticated users.
 Add redirect to login page when a non-logged-in user tries to book an event.
 Modify the backend API for booking events to validate that the user is authenticated and verified.
 Test with different user scenarios (logged-in, logged-out, verified, unverified).

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c397ea60-c46c-4e8c-85fa-9d6745828318)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad assigned

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal can I work on this issue??

**Comment by RamakrushnaBiswal** [comment]
Sure @haseebzaki-07
