### ISSUE TITLE
Feat:  Fix Reservation Form Validation Error

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#299]
### Describe the feature

Description: The reservation form is currently throwing a validation error related to the email field. The error message indicates that the form is receiving undefined for the "email" field, while it expects a string. This needs to be resolved so that the form processes correctly when submitting a reservation.

Error:
json
[
    {
        "code": "invalid_type",
        "expected": "string",
        "received": "undefined",
        "path": [
            "email"
        ],
        "message": "Required"
    }
]
Acceptance Criteria:
The reservation form should correctly capture and validate the email field as a string.
The form should no longer throw the above validation error during submission.
Test the form to ensure the error doesn't occur for valid email inputs.

Tasks:
 Investigate why the email field is receiving undefined instead of a string.
 Fix the form logic to correctly handle and validate the email field.
 Ensure the email input is properly connected to the state and sent to the backend.
 Test to confirm that the error is resolved.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/38a15275-8f90-4f3a-aeb4-68379f33082f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
assigned @samar12-rad

**Comment by Sourabh782** [comment]
@RamakrushnaBiswal i see this issue vacant for 2 weeks, if its free can i look into it?
