### ISSUE TITLE
BUG: I was Logged IN Still was unable to give feedback | gssoc-ext | level 3

### ISSUE THREAD

**Issue by Hamza1821** [RamakrushnaBiswal/PlayCafe#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I was Logged IN Still was unable to give feedback

screenshot
![Screenshot 2024-10-15 at 20-53-28 BoardGame Cafe](https://github.com/user-attachments/assets/b6cbd65e-c85f-40e5-89fe-f307fbcb8fad)

please assign this to me under gssoc-ext levl 3 as it is a backend issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Hamza1821 because your msg length is less that why its happens :)

**Comment by RamakrushnaBiswal** [comment]
@Hamza1821 if you can fix this create another issue
