### ISSUE TITLE
User Experience Enhancements | Blank Screen after last Card in Feedback Slider | BackToTop Button Hard Scroll to Top. 

### ISSUE THREAD

**Issue by Shariq2003** [RamakrushnaBiswal/PlayCafe#306]
The following issues need to addressed.

1. BackToTop Button Scrolling not Smooth?
Soln. :-> The button hard sets the Y value as 0 to sets at the top which should be solved by smooth animation of the value of Y changing 

2. Blank Screen after the last card of feedback.
Soln. :-> The card carousel should move in a circular manner that encounters the dead end.

https://github.com/user-attachments/assets/fb0e5cdf-874f-4630-a4e1-22befbcd4dc4

Please assign this to me.

**Comment by RamakrushnaBiswal** [comment]
duplicate as #302
