### ISSUE TITLE
BUG: Margin in footer section links must be adjusted

### ISSUE THREAD

**Issue by nishtha-902** [RamakrushnaBiswal/PlayCafe#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/52d229b8-347c-4ab0-83f8-7df92d7b6514)
Please assign me this issue 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@nishtha-902 i think its fine 
![Uploading image.png…]()
