### ISSUE TITLE
BUG: Horizontal scroll must be removed as website has blank space in right side

### ISSUE THREAD

**Issue by nishtha-902** [RamakrushnaBiswal/PlayCafe#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/d0cd5b57-3264-44a6-9b1a-e4312320e508)
please assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
hi @nishtha-902 
i didn't see it 
![image](https://github.com/user-attachments/assets/48f1bfde-73f7-4a20-bfa7-370a6a06f90f)
