### ISSUE TITLE
BUG: No proper margins in text and image in hero section of events page

### ISSUE THREAD

**Issue by nishtha-902** [RamakrushnaBiswal/PlayCafe#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/f82249dd-c049-4a68-b3d9-f53d95305867)
please assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate #277
