### ISSUE TITLE
BUG: Text overflown vertically in about us section

### ISSUE THREAD

**Issue by nishtha-902** [RamakrushnaBiswal/PlayCafe#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/32b515af-81c4-4a02-8160-e72a0da976ca)
please assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
i didn't see it
![image](https://github.com/user-attachments/assets/f03ec4c3-4488-4670-99f1-df52d46c873a)
