### ISSUE TITLE
BUG: Duplicate CORS Configuration and Typo in errorMiddleware Import

### ISSUE THREAD

**Issue by chikatlarakesh** [RamakrushnaBiswal/PlayCafe#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I encountered two bugs in the current codebase:

1. Duplicate CORS Configuration:
- There are two instances of app.use(cors(...)), which results in redundant middleware applications. This can cause conflicts and unnecessary processing.

2. Typo in errorMiddleware Import:
- The errorMiddleware file is imported with a typo as require("./middlewares/errrorMiddleware"). It should be corrected to require("./middlewares/errorMiddleware").

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@chikatlarakesh go for it
