### ISSUE TITLE
BUG: Add a logo that matches the website color combination and looks attractive 

### ISSUE THREAD

**Issue by Deepanshu-pathak** [RamakrushnaBiswal/PlayCafe#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

As i can see, the logo of website is not visible with current color combos and the text is very hard to read on the logo, i can make new logo with contrasting color combinations and make it pop out in the navbar to looks attractive
![Screenshot 2024-10-02 161504](https://github.com/user-attachments/assets/f1ae3956-255f-48a8-b74f-7db83c206a5d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Deepanshu-pathak well make a logo for our website

**Comment by Nvntdad** [comment]
@RamakrushnaBiswal Can i raise a PR about this if the already assigned person is not proposing the PR.

**Comment by RamakrushnaBiswal** [comment]
@Nvntdad  if he didn't completed till tommorow then i will assign it to you then you can contribute

**Comment by Deepanshu-pathak** [comment]
@RamakrushnaBiswal The logo is already made but the repo is not running in local host so i am not able to check dimensions of logo for the navbar. If u can help plz tell me what to do?

**Comment by RamakrushnaBiswal** [comment]
@Deepanshu-pathak follow this [this](https://github.com/RamakrushnaBiswal/PlayCafe#%EF%B8%8F-getting-started---installation)

**Comment by Nvntdad** [comment]
did he completed the task .

**Comment by Deepanshu-pathak** [comment]
@Nvntdad @RamakrushnaBiswal after many tries and tutorials, still it is not working on my localhost so i am sorry for that and you can take this issue, Thanku

**Comment by RamakrushnaBiswal** [comment]
did you installed node js in your PC @Deepanshu-pathak

**Comment by Deepanshu-pathak** [comment]
@RamakrushnaBiswal  yes i did, but nevermind you can assign it to @Nvntdad

**Comment by RamakrushnaBiswal** [comment]
yh ok @Deepanshu-pathak

**Comment by RamakrushnaBiswal** [comment]
assigned @Nvntdad

**Comment by RamakrushnaBiswal** [comment]
Solved via #85
