### ISSUE TITLE
Feat: Dark Mode

### ISSUE THREAD

**Issue by jainaryan04** [RamakrushnaBiswal/PlayCafe#322]
### Describe the feature

I want to add a toggle button that would allow the users to switch to dark mode.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4cf46bc2-8cff-4fd8-a14e-780bf1845b13)
![image](https://github.com/user-attachments/assets/cc813111-0d02-4bec-bc88-ea06fa3dc007)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go fo it @jainaryan04 
previous issue #37

**Comment by jainaryan04** [comment]
@RamakrushnaBiswal 
if this is fine, then I will go ahead with the other pages
![image](https://github.com/user-attachments/assets/7f6deac1-d364-4be1-956b-fd6cc36e3821)
![image](https://github.com/user-attachments/assets/2e8085d6-25fe-4e82-85b0-23ccf1b82b04)

**Comment by RamakrushnaBiswal** [comment]
@jainaryan04 yes

**Comment by BaniSinghgithub** [comment]
hello sir @RamakrushnaBiswal , can you assign this work to me.
