### ISSUE TITLE
BUG: Customer Feedback Carousel Scroll even if no feedback

### ISSUE THREAD

**Issue by shreysachani** [RamakrushnaBiswal/PlayCafe#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In the customer feedback section when we scroll to see customer reviews then one can see unnecessary scroll even after the feedbacks are over.

https://github.com/user-attachments/assets/0c501800-1459-49be-abd3-18845d201308

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by shreysachani** [comment]
Please assign this issue to me under hacktoberfest. Also, assign the appropriate tags and levels for this issue.

**Comment by RamakrushnaBiswal** [comment]
@shreysachani duplicate as #302
