### ISSUE TITLE
BUG: UI improvement for Price Display in Today's Special 

### ISSUE THREAD

**Issue by vaibhav-yerkar** [RamakrushnaBiswal/PlayCafe#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

There can be UI improvement for the pricing display of the Today's Sepecial

issue:
1. no bottom padding 
2. Original Price's text color not so subtle
3. Original Price's text size could be smaller bringing the Current Price more in focus

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/a725dc0c-93b8-4079-921b-cfb1ef6cb145">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
what you are going to add any example @vaibhav-yerkar

**Comment by vaibhav-yerkar** [comment]
These are my proposed designs : 

<img width="864" alt="image" src="https://github.com/user-attachments/assets/305da2d7-a1c0-4b63-b432-2c61d07a18f6">
<img width="735" alt="image" src="https://github.com/user-attachments/assets/51f62336-fc38-4ff2-9d7b-a1d0f7caf60d">

**Comment by vaibhav-yerkar** [comment]
if you find it appealing , let me know 
and also mention whether you want the text alignment to be centred or the left aligned

**Comment by RamakrushnaBiswal** [comment]
@vaibhav-yerkar go for 1st design ✔️
