### ISSUE TITLE
BUG: Messy UI of the feedback div

### ISSUE THREAD

**Issue by HemantBatra873** [RamakrushnaBiswal/PlayCafe#328]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What went down?

**Problem**
The UI on the feedback div doesn't fit properly . The image is way to bigger ans seems to take up al lot of space . It would be beeter if we made it small and give space to the rest of the text .

---

![play-cafe-issue](https://github.com/user-attachments/assets/49313afb-8208-48ae-88f9-242b02ab7cf2)

---

**Please assign this to me under hacktoberfest-accepted label and gssoc-ext label.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
duplicate as #259
