### ISSUE TITLE
Feat:Google translator

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RamakrushnaBiswal/PlayCafe#329]
### Describe the feature

It will change the language of whole website as we know in India even in world there are many language and our user can be from any place and some user doesn't understand english so it will be better if we provide them the content of our website in there native language

Please assign me i can work on this Default is english but user has a button on clicking he get option of language and we could select form that

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c628af5f-b8a8-4b2d-a0e8-94ce486994bb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Sawan-Kushwah go for it , Add more international languages
