### ISSUE TITLE
BUG:login page form not responsive

### ISSUE THREAD

**Issue by Shahharshii** [RamakrushnaBiswal/PlayCafe#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In the small and medum screens the login form is not responsive.

![image](https://github.com/user-attachments/assets/a546ca72-6978-40cb-a8d3-ead417754c3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [x] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
go for it @Shahharshii also do signup page responsive

**Comment by Shahharshii** [comment]
> go for it @Shahharshii also do signup page responsive

yes sure
