### ISSUE TITLE
BUG: carousal for the boardgames page/section

### ISSUE THREAD

**Issue by Shahharshii** [RamakrushnaBiswal/PlayCafe#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

carousal can be added to the boardgames section where in it becomes a good user experiene and can enhance the UI of the page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
not required @Shahharshii
