### ISSUE TITLE
BUG: Heroimage section responsiveness

### ISSUE THREAD

**Issue by Shahharshii** [RamakrushnaBiswal/PlayCafe#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The text os overlapping the images in the heroimage section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist 

![image](https://github.com/user-attachments/assets/4004e8df-3791-4519-88db-2c5970e47efa)

**Comment by BaniSinghgithub** [comment]
hello sir @RamakrushnaBiswal , can you pls assign this work to me
