### ISSUE TITLE
Hover effects on Review Section

### ISSUE THREAD

**Issue by Bhum-ika** [RamakrushnaBiswal/PlayCafe#337]
![image](https://github.com/user-attachments/assets/1de68980-ddc3-4616-af44-469a1d23c67d)

Your whole website have these hover effects on cards but this section lacks it.
I will add the best effects on this section

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by RamakrushnaBiswal** [comment]
No needed @Bhum-ika
