### ISSUE TITLE
Sign up form not working remains in Pending state

### ISSUE THREAD

**Issue by shubhagarwal1** [RamakrushnaBiswal/PlayCafe#339]
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/24a21af8-3ab0-424e-adb5-83f8ba0e156d">

**Comment by RamakrushnaBiswal** [comment]
I think it working @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> I think it working @shubhagarwal1

hey @RamakrushnaBiswal as of now the site has no toaster thing which notify user about the working so can i integrate thta
