### ISSUE TITLE
Adding chatbot support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [RamakrushnaBiswal/PlayCafe#340]
### Describe the feature

I want to add a chatbot to the website, which will be fine tuned for this website and help you solve user queries. Can you please assign me this  issues?.
@RamakrushnaBiswal 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Go for it @T-Rahul-prabhu-38
