### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [RamakrushnaBiswal/PlayCafe#341]
### Describe the feature

I want to add a page to showcase all the contributors of this website

### Add ScreenShots

@RamakrushnaBiswal can you assign me this issue,

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Ok go for it @T-Rahul-prabhu-38 
In footer create a link name - our contributors then redirect to that page

**Comment by shubhagarwal1** [comment]
Hey @RamakrushnaBiswal can i work on this task, as it is already been a week, i can raise PR by today, infact within in 1hr of assignment, actually my PR is ready

**Comment by RamakrushnaBiswal** [comment]
@shubhagarwal1 go for it rise a PR asap
