### ISSUE TITLE
Feat:Enchance testimonial section 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RamakrushnaBiswal/PlayCafe#342]
### Describe the feature

![image](https://github.com/user-attachments/assets/e92ffdd3-135c-4803-9c36-f98198677de8)

By adding stronger testimonials, we can build user trust, improve credibility, and significantly enhance the overall experience on our platform

### Add ScreenShots

![Screenshot 2024-10-18 191732](https://github.com/user-attachments/assets/52a65bb1-cc7d-49ce-81b1-77586772c118)

Something like this i can redesign it according to website theme and make it more beautiful
on clicking on the arrow cards slide with an animation with create great user impact 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Look's good ✔️
But change the colors acc to the UI
@Sawan-Kushwah
