### ISSUE TITLE
Feat:  adding hacktober fest logos to the readme

### ISSUE THREAD

**Issue by REHAN-18** [RamakrushnaBiswal/PlayCafe#343]
### Describe the feature

adding  hacktober fest logos to the readme & update  the readme

### Add ScreenShots

![Uploading Screenshot 2024-10-18 at 8.47.49 PM.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by REHAN-18** [comment]
assign me under gssoc 2k24

**Comment by RamakrushnaBiswal** [comment]
Good Idea @REHAN-18

**Comment by REHAN-18** [comment]
@RamakrushnaBiswal done !!

**Comment by RamakrushnaBiswal** [comment]
Solved via #346
