### ISSUE TITLE
Feat: Dedicated help and support page

### ISSUE THREAD

**Issue by Sumanbhadra** [RamakrushnaBiswal/PlayCafe#344]
### Describe the feature

I have noticed that there is no help page and no similar open issue. To enhance customer support and address common inquiries, we need to create a dedicated help page on our website. This page should include a frequently asked questions (FAQ) section to provide quick answers to common queries and a complaint/feedback form to gather customer input and improve our services.

### Add ScreenShots

![Screenshot 2024-10-15 190351](https://github.com/user-attachments/assets/fdca12a6-b46a-43b4-88fc-0928b2413d3e)
![Screenshot 2024-10-17 125852](https://github.com/user-attachments/assets/d6f69653-0404-45bd-b1e4-409dd18ebf08)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Add the link to the page in footer @Sumanbhadra
