### ISSUE TITLE
Feat: Contact us floating button on home page 

### ISSUE THREAD

**Issue by AnushkaGupta2003** [RamakrushnaBiswal/PlayCafe#347]
### Describe the feature

A "Contact Us" floating button improves user accessibility and engagement by providing easy, always-visible access to support. It enhances user experience without disrupting browsing, encourages interaction, and is especially useful on mobile devices. It can also boost lead generation and conversions by simplifying communication with potential customers.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f372f223-75d2-4eac-ae60-d8fab46dd14a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@AnushkaGupta2003 duplicate as #201
