### ISSUE TITLE
BUG: Unintended Page Reloads on Footer Link Click

### ISSUE THREAD

**Issue by Sumanbhadra** [RamakrushnaBiswal/PlayCafe#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When a user clicks on a link within the footer of a React application, the entire page is unexpectedly reloaded instead of triggering a navigation within the application. 

Clicking on a footer link should trigger navigation within the application, update the URL, and render the appropriate component without reloading the entire page.

https://github.com/user-attachments/assets/76c48c00-cb20-46a1-be1f-6132286da345

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
go for it @Sumanbhadra
