### ISSUE TITLE
Feat: Addition of a mini clock in the navbar

### ISSUE THREAD

**Issue by Jay-1409** [RamakrushnaBiswal/PlayCafe#350]
### Describe the feature

I thought it would be a good idea to have a clock in the navbar, it looks cool

### Add ScreenShots

![image](https://github.com/user-attachments/assets/720fbc34-9b8b-48de-9f03-df891e4537ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by PriyanshuValiya** [comment]
@Jay-1409 Assign me this issue..

**Comment by RamakrushnaBiswal** [comment]
@Jay-1409 no man the navbar going too massy
