### ISSUE TITLE
BUG: Footer is fixed in every page 

### ISSUE THREAD

**Issue by HAIDER072** [RamakrushnaBiswal/PlayCafe#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when we  move to other pages like event, menu,reservation, etc when we scroll down footer is relatively positioned 
![BoardGame Cafe - Google Chrome 19-10-2024 16_56_20](https://github.com/user-attachments/assets/910e7528-7389-4058-9c84-668f1d7fec36)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [ ] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@HAIDER072 its there check once
