### ISSUE TITLE
Feat: User Experience Enhancements | Smooth Scrolling Addition of BackToTop Button | Customisation of Side Scrollbar (Theme Matched)

### ISSUE THREAD

**Issue by Shariq2003** [RamakrushnaBiswal/PlayCafe#358]
### Describe the feature

These are the Features that I will be going to implement:-

1. Smooth Scrolling Addition of BackToTop Button.
2. Customisation of the side Scrollbar that will match with the Theme of the website.the 

### Add ScreenShots

https://github.com/user-attachments/assets/4e10e253-3714-4c20-8a97-7e514363282a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
for me its work fine @Shariq2003

**Comment by Shariq2003** [comment]
> for me its work fine @Shariq2003

Okay sir, I think its a browser dependency issue.
