### ISSUE TITLE
Topic: ADD HACKTOBERFEST AND GSSOC BANNER ON THE README FILE

### ISSUE THREAD

**Issue by alo7lika** [RamakrushnaBiswal/PlayCafe#359]
### Describe the types of topics you'd add in our Website

Adding Hacktoberfest and GSSoC banners to the README file can greatly enhance the visibility and appeal of your repository by highlighting participation in these prestigious open-source events. Hacktoberfest, organized by DigitalOcean, encourages contributors to engage in the open-source community by making meaningful contributions throughout October. Similarly, GSSoC (GirlScript Summer of Code) promotes gender equality in tech by offering contributors the opportunity to work on real-world projects over three months. Including these banners in the README not only promotes the events but also attracts new contributors by creating a welcoming and inclusive environment. It encourages participation through visible calls to action, guiding contributors to repositories participating in these programs and offering valuable rewards like learning opportunities, networking, and even exclusive swag. By adding these elements, you also foster community engagement and inspire potential contributors to explore, learn, and contribute effectively to your open-source projects.

### Could you share some screenshots or a video of your previous work?

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by alo7lika** [comment]
assign me the task under gssoc and hacktoberfest @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
Solved #346

**Comment by RamakrushnaBiswal** [comment]
Ref #343
