### ISSUE TITLE
BUG: Event section calender text overflowing

### ISSUE THREAD

**Issue by Nvntdad** [RamakrushnaBiswal/PlayCafe#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I was just wandering on the mobile preview and i found this issue.

![be](https://github.com/user-attachments/assets/d1b6010c-af79-453e-bea0-1ab09748d773)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
not needed for now @Nvntdad
