### ISSUE TITLE
Feat: while registering the alert message come that is not suited on your website.

### ISSUE THREAD

**Issue by VinayLodhi1712** [RamakrushnaBiswal/PlayCafe#360]
### Describe the feature

Adding a good pop up message while signing in and login of a user not a default chrome alert.

### Add ScreenShots

![prompt](https://github.com/user-attachments/assets/70b7a10b-7058-4744-8684-a87fa29817bd)

i will add like Login Successfull/Sign up successfull type with bootstrap pop up message.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
got it @VinayLodhi1712 
add the antd _message_ here
