### ISSUE TITLE
Feat: Backend for feedback

### ISSUE THREAD

**Issue by haseebzaki-07** [RamakrushnaBiswal/PlayCafe#362]
### Describe the feature

user submitting their feedbacks should get a confirmation message also their feedback should reflect in the database for the respective users. I want to add the necessary controllers and routes for the purpose.

### Add ScreenShots

![Screenshot 2024-10-20 160244](https://github.com/user-attachments/assets/835b5637-9c73-4270-92cb-87ac9707519d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07  hy its already there but the maxm size of message it 10 but you give 4-5 thats why its coming
you can add the validation here , if yiu want to work tell me

**Comment by haseebzaki-07** [comment]
@RamakrushnaBiswal sure I will add validation.

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal should I proceed!

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal please reply

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 sorry for late
assigned
