### ISSUE TITLE
Feat: Book your slot for event

### ISSUE THREAD

**Issue by haseebzaki-07** [RamakrushnaBiswal/PlayCafe#363]
### Describe the feature

I want to add the implementation of booking slots for a event. I will write the necessary controllers and APIs for the purpose so that a user booking the slot gets a confirmation message and he is associated with the booking in the database.

### Add ScreenShots

![Screenshot 2024-10-20 160741](https://github.com/user-attachments/assets/27bd112b-09ed-4921-a2d8-3519bd4f3514)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
ok go for it @haseebzaki-07
