### ISSUE TITLE
Feat: [UI/UX-Enhancement]-Adding Dark Mode and Adding 

### ISSUE THREAD

**Issue by AdityaP700** [RamakrushnaBiswal/PlayCafe#37]
### Adding a Dark Mode Button
The current color scheme of the webpage is visually decent; however, to enhance user comfort, it would be beneficial to implement a Dark Mode. This option could be integrated into the NavBar, allowing users to easily switch between light and dark modes. This feature will make the interface more visually appealing and user-friendly, especially in low-light conditions.

###Add Type-writter effect 
To enhance the appeal of the Title page, a typewriter effect can be used for the main headline. The effect could start with the text A unique café experience awaits you... followed by a smooth transition to the café name PlayCafe and then the tagline "Crafted with passion, brewed with love."

### Dark Mode 
![image](https://github.com/user-attachments/assets/5c664f48-caf9-48d0-980a-5977c129bb25)
### TypeWriter effect
![image](https://github.com/user-attachments/assets/03da7e7e-08b4-4745-b9e3-460256b0a33f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by AdityaP700** [comment]
Thanks for assigning the issue , would surely make the necessary fixes and attach the video while raising the PR .

**Comment by RamakrushnaBiswal** [comment]
@AdityaP700 use it ( https://darkmodejs.learn.uno/ )

**Comment by RamakrushnaBiswal** [comment]
@AdityaP700 you are not working so i will assign the issue someone else 
ref #322
