### ISSUE TITLE
BUG:Footer getting overshadowed by the main content on scroll

### ISSUE THREAD

**Issue by omkar861856** [RamakrushnaBiswal/PlayCafe#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The main content overshadows the footer when scroll reaches the bottom. @RamakrushnaBiswal 

Attached a video for the issue - Skip to 14 seconds for the issue.

https://github.com/user-attachments/assets/331f828b-19fe-4082-8e69-2b40a1b5f90f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
#357 duplicate
