### ISSUE TITLE
Topic: Updation of Code_of_conduct file

### ISSUE THREAD

**Issue by Nikhil0-3** [RamakrushnaBiswal/PlayCafe#371]
### Describe the types of topics you'd add in our Website

Wanted to do the following changes :-

How to contribute (fix bugs, add features)
Steps for submitting changes
Project setup instructions
Rules for code style
Code of conduct for respectful behavior
Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by RamakrushnaBiswal** [comment]
go for it @Nikhil0-3
