### ISSUE TITLE
BUG: Horizontal Scrolling in home page

### ISSUE THREAD

**Issue by Gauravtb2253** [RamakrushnaBiswal/PlayCafe#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

There is horizontal scrolling in the website

![image](https://github.com/user-attachments/assets/fcd1146c-7075-4642-a0d9-463793fac6ae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Gauravtb2253 it works fine for me
