### ISSUE TITLE
Revamp Your Website: Stylish Navbar Menu for Contributing to an Open-Source Project for a Sleek and Modern Design

### ISSUE THREAD

**Issue by khurshed07** [RamakrushnaBiswal/PlayCafe#383]
# Before Changes:
![Screenshot 2024-10-22 154425](https://github.com/user-attachments/assets/fb8e7a1b-048c-4d07-90f9-170567d3d7a9)
![Screenshot 2024-10-22 154434](https://github.com/user-attachments/assets/2d152749-35dc-438e-91da-fe2ea0b01c3d)

# After Changes:
![Screenshot 2024-10-22 153724](https://github.com/user-attachments/assets/25132581-ee0f-480a-a7ad-7f832c3a5f2e)
![Screenshot 2024-10-22 153730](https://github.com/user-attachments/assets/6dedf0d5-8836-4a0c-aa0b-edf4f44fda23)
![Screenshot 2024-10-22 153739](https://github.com/user-attachments/assets/f7e89c31-471d-48a6-9811-791f314e0acd)
![Screenshot 2024-10-22 153748](https://github.com/user-attachments/assets/78068d66-2407-4b6f-a207-4c0576ec766f)
![Screenshot 2024-10-22 153757](https://github.com/user-attachments/assets/6ba57be7-c902-459c-9644-247c3512df39)
![Screenshot 2024-10-22 153805](https://github.com/user-attachments/assets/19e17435-530a-4910-a0a5-f3d0422b17e3)
![Screenshot 2024-10-22 154256](https://github.com/user-attachments/assets/e896ad1c-5aaa-40b8-9e6e-386c03cd0720)
![Screenshot 2024-10-22 154302](https://github.com/user-attachments/assets/a739f2c8-90fa-427e-81db-21150bbd6574)
![Screenshot 2024-10-22 154307](https://github.com/user-attachments/assets/76771f78-52c6-4016-b4a7-16742596a999)
![Screenshot 2024-10-22 154314](https://github.com/user-attachments/assets/6f6a92d4-4bde-434f-9510-7d2414ee0e9b)
![Screenshot 2024-10-22 154319](https://github.com/user-attachments/assets/a181dfd5-ad59-498d-b6f7-4fdd858a9e9e)
![Screenshot 2024-10-22 154328](https://github.com/user-attachments/assets/55cfaf9b-f494-4cbb-931f-5553bbf7ac99)

Hi @RamakrushnaBiswal 
I recently updated the navbar menu for your project to make it more attractive and user-friendly. Enhance readability, improve navigation, and give your site a visually appealing touch that stands out with these simple yet impactful design updates. I've attached screenshots of the changes, and I'd love to contribute to this enhancement to improve the overall design.

Please assign me to this task. It would be a great opportunity to contribute while enhancing my skills.

I'm looking forward to hearing back from you!
Best regards,
@khurshed07
https://github.com/khurshed07

**Comment by RamakrushnaBiswal** [comment]
@khurshed07 i don't think is looks good
