### ISSUE TITLE
Feat: lets add some review section that feels so real, with images and experience

### ISSUE THREAD

**Issue by Jigyasa182** [RamakrushnaBiswal/PlayCafe#384]
### Describe the feature

as i saw , we have a feedback section , but lets improvise and make it more realistic , that can be trusted more like posting personal experience with food , games , personal pictures.
that will surely increase the interactive side of our website.

### Add ScreenShots

![Screenshot 2024-10-22 203548](https://github.com/user-attachments/assets/9346df93-8d34-4a24-949c-8f6d8c3f22d6)

kinda like these and possibly more in a creative manner , i will try.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
not needed @Jigyasa182
