### ISSUE TITLE
BUG: Copyright Part not visible

### ISSUE THREAD

**Issue by harjasae2001** [RamakrushnaBiswal/PlayCafe#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![{42DC7C21-429B-41B6-A7EB-A7F43ACBB0A4}](https://github.com/user-attachments/assets/9d84a3dd-6cdd-4673-9419-b760e13bf7c3)
 Copyright part not visible with the name due to chatbot logo.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
go for it @harjasae2001

**Comment by harjasae2001** [comment]
@RamakrushnaBiswal Pls review my PR.
