### ISSUE TITLE
Feat: Add a Subscribe Section to the Events Page

### ISSUE THREAD

**Issue by Mohitranag18** [RamakrushnaBiswal/PlayCafe#387]
### Description:
We would like to enhance user engagement by adding a "Subscribe" section on the Events page. This feature will allow users to stay informed about upcoming events, including game nights, tournaments, and special events.

### Proposed Implementation:

**Subscribe Section Title:**
"Stay Updated!"

**Description:**
"Subscribe to our newsletter to be the first to know about exciting game nights, tournaments, and special events!"

**Fields:**
Name (Input Field)
Email (Input Field)

**Button:**
"Subscribe Now"

### Benefits:

- Encourages users to join our mailing list.
- Keeps the subscription process simple and user-friendly.
- Increases engagement and participation in future events.

### Acceptance Criteria:

- The subscribe section is visually appealing and matches the overall design of the Events page.
- Form validation ensures that the Name and Email fields are properly filled out before submission.
- On successful submission, users receive a confirmation message.

### Storage:
All user inputs will be stored in a subscriber file, creating a list of subscribers for future communications.

### Add ScreenShots

![subscribe feat](https://github.com/user-attachments/assets/09f2feb5-24c3-4d77-bd56-ab0111eb11d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by Mohitranag18** [comment]
@RamakrushnaBiswal please assign this issue to me i will make it.

**Comment by RamakrushnaBiswal** [comment]
not needed @Mohitranag18
