### ISSUE TITLE
Feat: add hover effect on the navbar options and use better fonts.

### ISSUE THREAD

**Issue by Ayush215mb** [RamakrushnaBiswal/PlayCafe#39]
### Describe the feature

I can add a hover effect on the navbar options, use a better font, will add some spacing so it looks more classy and the favicon is also missing so will also do that. 
Please assign me this and I will do all the changes and create a PR request in a hour.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/14a20067-0950-4175-9c22-0390ad66984c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Already assigned to someone #5

**Comment by Ayush215mb** [comment]
okay np with that, but if you want it to be done asap then you can tell me.
I will create a better navbar in a hour and send a PR.

**Comment by RamakrushnaBiswal** [comment]
ok if if he will not do that on time i will assign you

**Comment by RamakrushnaBiswal** [comment]
@Ayush215mb assigned

**Comment by Ayush215mb** [comment]
@RamakrushnaBiswal  shall i add the hover effect as well?

**Comment by RamakrushnaBiswal** [comment]
> @RamakrushnaBiswal shall i add the hover effect as well?

where in navabr ?

change the fonts of munu page

**Comment by Ayush215mb** [comment]
![image](https://github.com/user-attachments/assets/232677a7-24c7-4eee-b793-a90ad56c3a95)
Is the font to your liking??

**Comment by Ayush215mb** [comment]
https://github.com/user-attachments/assets/982ed494-c4fd-4375-bdf2-66b50202f048
 @RamakrushnaBiswal  tell me if this is to your liking, then i will create the PR

**Comment by RamakrushnaBiswal** [comment]
ok add the hover effect but change the hovering color don't change the font 

in menu page use the same font as in landing page

**Comment by Ayush215mb** [comment]
@RamakrushnaBiswal  which color should i add ?
according to me I tried to use best color combination, other color stands out more(in a bad way) and I'm changing the fonts of menu page.

**Comment by RamakrushnaBiswal** [comment]
ok then @Ayush215mb

**Comment by RamakrushnaBiswal** [comment]
solved via #103
