### ISSUE TITLE
ADD Github Contributors page to the web application 

### ISSUE THREAD

**Issue by shubhagarwal1** [RamakrushnaBiswal/PlayCafe#392]

**Comment by RamakrushnaBiswal** [comment]
@shubhagarwal1 duplicate

**Comment by shubhagarwal1** [comment]
hey @RamakrushnaBiswal can you please tell me some tasks which i can work on, i would be a great opportunity for me .

**Comment by RamakrushnaBiswal** [comment]
@shubhagarwal1 check old issues and comment there i will assign
