### ISSUE TITLE
Feat: Improving hover effect in about section and socials (icons)

### ISSUE THREAD

**Issue by tanishirai** [RamakrushnaBiswal/PlayCafe#393]
### Describe the feature

In light mode hover effect makes text white and is not visible 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3e17746b-442a-45f3-87b8-d09ba16bb548)
Facebook is hovered and is not visible due to white colour 
![image](https://github.com/user-attachments/assets/53ed562b-f3b7-4916-a1ff-41ec0df9f859)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@tanishirai not needed
