### ISSUE TITLE
Feat: Improve the events page, specifically the upcomming events section

### ISSUE THREAD

**Issue by Jay-1409** [RamakrushnaBiswal/PlayCafe#396]
### Describe the feature

I would like to add upcomming events 
Some examples
- Game Night Extravaganza
Date: 2024-11-04
Time: 7:00 PM - 10:00 PM
Description: Join us for an exciting game night featuring classic board games like Monopoly, Scrabble, and Risk. Enjoy food and drinks while competing for the top spot!

- Family Fun Day
Date: 2024-11-10
Time: 12:00 PM - 5:00 PM
Description: A day packed with fun for families! Participate in friendly board game competitions, enjoy delicious snacks, and make unforgettable memories.

- Trivia Night
Date: 2024-11-18
Time: 6:30 PM - 9:30 PM
Description: Test your knowledge with a trivia night challenge while enjoying great food and drinks. Special prizes for the winning teams!

THanks for hearing me out!!

### Add ScreenShots

![image](https://github.com/user-attachments/assets/475c5fb5-1e1d-48e7-b9a3-a25429ee1fcb)
This is the component more specifically that i would like to change. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
its not an issue
