### ISSUE TITLE
BUG:Image not displaying properly.

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [RamakrushnaBiswal/PlayCafe#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/e70fc2ac-f831-4f26-8488-ed48924e1162)
Currently the image is not linked properly because of which the image is not displayed.
Please assign the issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@Vaibhav-Kumar-K-R assigned

**Comment by Vaibhav-Kumar-K-R** [comment]
@RamakrushnaBiswal 
The image specified in  the src attribute is not available in any of the images under the assets folder.
Would u like to add a new image instead??

**Comment by Vaibhav-Kumar-K-R** [comment]
i have linked a pull  request referenced #17 .
Please review it

**Comment by RamakrushnaBiswal** [comment]
@Vaibhav-Kumar-K-R #17  merged
