### ISSUE TITLE
Feat: Implementation for ordering of food

### ISSUE THREAD

**Issue by haseebzaki-07** [RamakrushnaBiswal/PlayCafe#400]
### Describe the feature

Add backend implementation for ordering of food by the users. Also associate the users with their orders in the database.
Necessary for order management of the website.

### Add ScreenShots

![Screenshot 2024-10-26 001321](https://github.com/user-attachments/assets/8403f9f0-d6e3-4af8-af2e-d65e32fbfd0f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @haseebzaki-07
