### ISSUE TITLE
Project Proposal: Memory game

### ISSUE THREAD

**Issue by Mansi07sharma** [RamakrushnaBiswal/PlayCafe#403]
### Overview

Cards memory game is a board game

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this project proposal
- [X] It is not duplicate

**Comment by RamakrushnaBiswal** [comment]
@Mansi07sharma give more details
