### ISSUE TITLE
BUG: fix the main page footer non res.

### ISSUE THREAD

**Issue by AE-Hertz** [RamakrushnaBiswal/PlayCafe#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The existing issue has no updates and no work for more than a week. This issue will focus on changes of the specific part see attachment. 
Make the text clipping to responsive design.

![Screenshot_2024-10-27-02-01-17-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/5a50dbae-725f-405b-b95b-3485395a9082)

Assign me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
go for it @AE-Hertz
