### ISSUE TITLE
[Feat]  Creating a Carousel for Today's Special Menu Items

### ISSUE THREAD

**Issue by IkkiOcean** [RamakrushnaBiswal/PlayCafe#407]
### Describe the feature

To enhance the user experience on the menu page, I plan to implement a carousel feature that will showcase today's special menu items. This interactive element will allow customers to easily view special offers and enticing dishes in a visually appealing manner. 

### Proposed Carousel Feature

- **Dynamic Display**: The carousel will be capable of showcasing more than just three recipes, allowing for a wider selection of today's specials. This will not only provide variety but also keep the content fresh and engaging for returning customers.

- **Interactive Navigation**: Users will be able to navigate through the special dishes using intuitive controls. Features like next/previous arrows and pagination dots will enable easy browsing.

- **Autoplay Option**: The carousel can automatically transition between items after a set duration, ensuring that all special dishes are highlighted without requiring user input. Customers can also pause the autoplay to focus on a particular item.

- **Responsive Design**: The carousel will be fully responsive, ensuring it looks great on all devices, including desktops, tablets, and smartphones. This accessibility will improve the user experience across platforms.

- **Enhanced Visuals**: Each special dish will be presented with high-quality images, accompanied by enticing descriptions and prices. This will attract users' attention and encourage them to explore the offerings further.

### Current status

<img width="914" alt="Screenshot 2024-10-27 at 3 56 35 AM" src="https://github.com/user-attachments/assets/d9801bad-69cc-4bcb-8104-5515b5264efc">

This is static limiting to amount of item which can be shown

## this is a demo, actually component will be catering to BoardGame Cafe's Needs, Content and UI

<img width="1172" alt="Screenshot 2024-10-27 at 3 54 42 AM" src="https://github.com/user-attachments/assets/2f85f400-4017-400e-9fda-6b9b114ae258">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@IkkiOcean go for it
