### ISSUE TITLE
Feat: Adding animation on the home page.

### ISSUE THREAD

**Issue by RchtDshr** [RamakrushnaBiswal/PlayCafe#41]
### Describe the feature

I want to add animation for PLAYCAFE section of the page for which the coffee image appears from behind concurrently the word PLAY appears from left and CAFE from right which creates a smooth animation. I also want to add animation for the Landing Page which has typing text animation with opacity and images appears with animation too. I will be using GSAP for creating the required animation effects.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1d1b15d8-5804-498c-834e-49deffee5f08)
![image](https://github.com/user-attachments/assets/61b03cb7-7ace-4470-b171-ab6fedb2c3f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
well send some examples
