### ISSUE TITLE
Feat:  Add Stargazers and Forkers Profiles to README.md ✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [RamakrushnaBiswal/PlayCafe#410]
### Describe the feature

To showcase community engagement and make the project more interactive, add the stargazers and workers profiles to the README.md, as shown in the screenshot.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4da5c285-87c6-49f9-91c5-9007f0c2e94b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @AnushkaChouhan25

**Comment by AnushkaChouhan25** [comment]
@RamakrushnaBiswal Done

**Comment by praneethaBrindavanam** [comment]
please assign issue
