### ISSUE TITLE
Improve Footer Text Visibility in Light Theme

### ISSUE THREAD

**Issue by AnushkaChouhan25** [RamakrushnaBiswal/PlayCafe#411]
The footer text in the light theme is not properly visible, making it difficult for users to read. I propose modifying the text color and style to enhance readability and ensure consistency with the overall design of the website.

![image](https://github.com/user-attachments/assets/0e31adba-6420-43ba-a695-15783038a43d)

**Comment by RamakrushnaBiswal** [comment]
go for it @AnushkaChouhan25

**Comment by AnushkaChouhan25** [comment]
Hello @RamakrushnaBiswal, Can I Solve two issues together, this one and #412, and make changes in only one commit, So can you give level 2 for it?

**Comment by RamakrushnaBiswal** [comment]
yh sure

**Comment by AnushkaChouhan25** [comment]
@RamakrushnaBiswal Done👍
