### ISSUE TITLE
Feat: Revamp Theme Toggle Button Design and Icons

### ISSUE THREAD

**Issue by AnushkaChouhan25** [RamakrushnaBiswal/PlayCafe#412]
### Describe the feature

 I propose to change the design of the theme toggle button sun and moon icons. The current design could be improved for better aesthetics and usability, making it more visually appealing and intuitive for users.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a215676b-8d42-4790-9df0-951fc4dfddc2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @AnushkaChouhan25
