### ISSUE TITLE
Feat: Improving Slide Icon Hover Animation for consistent and smooth animation

### ISSUE THREAD

**Issue by CoderFleet** [RamakrushnaBiswal/PlayCafe#415]
### Describe the feature

The current hover animation on the slide icons in the Customer Feedback section feels inconsistent and does not blend seamlessly with the rest of the webpage design. The existing effect, which involves shrinking and color changes, disrupts the visual harmony of the section.

Proposed Solution:
Replace the shrink and color-change animation with a subtle slide animation on hover. This will create a smoother and more cohesive look, enhancing the user experience

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1e0cdf1c-79ab-4b92-95c8-74005e846929)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@CoderFleet go for it

**Comment by CoderFleet** [comment]
Thank You @RamakrushnaBiswal for assigning, I have started working on it

**Comment by CoderFleet** [comment]
Hi! Wanted to ask your preference on this
Which one hover color would you like 
![image](https://github.com/user-attachments/assets/a7b7a123-1dfc-49d6-8c8d-2e7d5dd73eac)
![image](https://github.com/user-attachments/assets/6a941b73-a858-4326-8699-e094671356c3)

The first one matches the website's theme colours but looks a little pale in dark mode, 
While the second one is a little brighter version of the current UI colour, it looks better with the current hover animation
Lemme Know...
