### ISSUE TITLE
Feat: Improve Button Readability in Dark Theme for Events Slot Booking Section

### ISSUE THREAD

**Issue by CoderFleet** [RamakrushnaBiswal/PlayCafe#417]
### Describe the feature

**Description:**  
In the Events section, specifically within the Slot Booking area, the button appearance currently displays effectively in light theme. However, in dark theme, the button does not adapt its colors, which creates readability issues due to low contrast between the button text and background. Improving the button’s color adaptation for dark theme will enhance accessibility and maintain a consistent user experience across themes.

**Steps to Reproduce:**  
1. Navigate to the Events section using navbar.
2. Switch to dark theme.
3. Observe the Slot Booking button and note the readability issues due to color contrast.

**Expected Behavior:**  
The button should dynamically adjust to dark theme, using colors that ensure readability and visual consistency with other dark theme elements.

**Proposed Solution:**  
Implement color adaptations for the Slot Booking button in dark theme to increase text-background contrast. This may involve:
- Modifying button background and text colors specifically for dark theme.
- Ensuring accessibility standards by achieving sufficient contrast ratio.

**Screenshots:**  
![image](https://github.com/user-attachments/assets/3cb52a81-a116-48b6-a8ab-ed80b97be4a0)
![image](https://github.com/user-attachments/assets/7382dfe1-7a35-480f-8b04-4a0b48a4aa81)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/15f951af-76dc-417e-baf4-212a82ff1655)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
go for it @CoderFleet

**Comment by CoderFleet** [comment]
Thanks! Started working on it
