### ISSUE TITLE
Project Proposal: Add 2 more games

### ISSUE THREAD

**Issue by Mansi07sharma** [RamakrushnaBiswal/PlayCafe#420]
### Overview

Can I add 2 more games in your boradgame section so that it will look more good as compare to 1??

The name of game Mysterium and Connect four??

Mysterium - A cooperative mystery game where players work together to interpret clues and solve a murder.
Connect Four - A classic two-player game where players take turns dropping colored discs into a vertical grid, aiming to be the first to align four of their discs in a row—vertically, horizontally, or diagonally.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this project proposal
- [X] It is not duplicate

**Comment by RamakrushnaBiswal** [comment]
@Mansi07sharma nope not required this
