### ISSUE TITLE
Feat: Add Event Booking

### ISSUE THREAD

**Issue by haseebzaki-07** [RamakrushnaBiswal/PlayCafe#428]
### Describe the feature

Add the frontend page for event Booking and integrate with the backend API.

### Add ScreenShots

![Screenshot 2024-10-29 133108](https://github.com/user-attachments/assets/4a27c6f4-e224-457b-bbe9-02913bbf48ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
it is same as the register event form so not needed
