### ISSUE TITLE
FIXING Stargazers and Forkers section IN README.MD

### ISSUE THREAD

**Issue by amiya-cyber** [RamakrushnaBiswal/PlayCafe#429]
fixing it by making the photos visible as well as adding some more attractive lines

now
![2024-10-29 (2)](https://github.com/user-attachments/assets/474b51a4-f890-40d9-ae61-cb173d2d088b)

changes i want to make
![2024-10-29 (1)](https://github.com/user-attachments/assets/d70cb906-4702-48a5-adb9-d066fdece408)

please assign @RamakrushnaBiswal and add level 2 label as i am fixing it

**Comment by RamakrushnaBiswal** [comment]
go for it
