### ISSUE TITLE
Feat : User Registration kinde Auth

### ISSUE THREAD

**Issue by 17arindam** [RamakrushnaBiswal/PlayCafe#43]
### Describe the feature

I want to integrate user registration into this website from which user can register themselves . 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7d1b50bb-c75a-4652-8f06-b425ef79c7bb)
like this i want to add user registration page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
can you know about kinde
auth

**Comment by 17arindam** [comment]
@RamakrushnaBiswal i havent used kinde auth yet but i can try i will give my best if you assign me this issue

**Comment by RamakrushnaBiswal** [comment]
ok @17arindam assigned add the button in top navbar then kinde automatically redirect to the page

**Comment by RamakrushnaBiswal** [comment]
solved via #71
