### ISSUE TITLE
footer layout for mobile 

### ISSUE THREAD

**Issue by jainaryan04** [RamakrushnaBiswal/PlayCafe#434]
the content is not centered. left margin is more than right margin.
centre the two divs in the viewport width
also, centre the contact us div 
@RamakrushnaBiswal ![Screenshot_2024-10-29-23-04-09-56_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/03ac5ad1-5772-4bab-8755-28738c925bc1)

**Comment by RamakrushnaBiswal** [comment]
Go for it ⚡ 
@jainaryan04
