### ISSUE TITLE
Feat: Beverages Section

### ISSUE THREAD

**Issue by NK-Works** [RamakrushnaBiswal/PlayCafe#443]
### Describe the feature

Add a dedicated beverages section showcasing snacks that will come.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0e2b5217-7ff8-4c12-aca3-1ea146ee54e2)
Here in the menu section only show best sellings combos and at the end put a button to go to the beverages section to explore all beverages....
This will make the menu efffective for regular users while beverages section is for new people to select theri favorite meal and make theri personal combos.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@NK-Works not needed for now
