### ISSUE TITLE
Feat: Add User details and booked events to the profile page.

### ISSUE THREAD

**Issue by haseebzaki-07** [RamakrushnaBiswal/PlayCafe#444]
### Describe the feature

User will be able to see their profile and their booked events to the profile page.

### Add ScreenShots

![Screenshot 2024-11-01 132932](https://github.com/user-attachments/assets/7b753849-80dd-411c-aa99-e93ccfc574cc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Go for it ⚡ @haseebzaki-07
