### ISSUE TITLE
Feat:Want ot add the security

### ISSUE THREAD

**Issue by Dipanita45** [RamakrushnaBiswal/PlayCafe#448]
### Describe the feature

Security of the website

### Add ScreenShots

No screenshots

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Dipanita45 what you are going to add

**Comment by Dipanita45** [comment]
I will add necessary security to protect the website against the harms

**Comment by RamakrushnaBiswal** [comment]
go for it @Dipanita45
