### ISSUE TITLE
BUG: Text and Image Overlap in Bottom Section Near Feedback When Language Set to Telugu

### ISSUE THREAD

**Issue by HarshithaSivalingala** [RamakrushnaBiswal/PlayCafe#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When the application language is changed to Telugu, the text and image in the bottom section, near the feedback area, overlap. This affects readability and impacts the visual presentation of the page.
<img width="625" alt="Screenshot 2024-11-02 at 10 00 19 PM" src="https://github.com/user-attachments/assets/f96340a5-648a-48d4-a558-e6e26b3ef127">
<img width="1293" alt="Screenshot 2024-11-02 at 10 00 06 PM" src="https://github.com/user-attachments/assets/d4e1622b-2ee9-4189-9caa-d40eda66a099">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@HarshithaSivalingala not needed
