### ISSUE TITLE
BUG: Arrow Buttons Visible at Carousel Start and End Positions

### ISSUE THREAD

**Issue by HarshithaSivalingala** [RamakrushnaBiswal/PlayCafe#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

 The carousel displays a left arrow even when it is at the first card and a right arrow when it is at the last card. This is confusing for users, as these arrows suggest navigation in directions where no additional content exists. Ideally, the left arrow should be hidden when on the first card, and the right arrow should be hidden when on the last card.
<img width="1297" alt="Screenshot 2024-11-02 at 9 57 42 PM (1)" src="https://github.com/user-attachments/assets/3721ec8e-5605-424d-bb17-eee8b6246af0">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-ext contributor
- [X] I have starred the repository
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
@HarshithaSivalingala go for it
