### ISSUE TITLE
BUG: Fixing  the about and slider bar issue

### ISSUE THREAD

**Issue by sajalbatra** [RamakrushnaBiswal/PlayCafe#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I have attached the images and these issues should be resolved for all the screens.
![image](https://github.com/user-attachments/assets/623433c9-f260-4a0a-9de9-ca3002b46f04)
![image](https://github.com/user-attachments/assets/95e2e7fc-ae45-42b4-bdd2-5bb8c493f5d2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a gssoc-24-extd contributor
- [x] I want to work on this issue
- [x] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
well  @sajalbatra 
fix the following : -
1.vertical extra margin
2.horizontal extra margin 
3.make this part responsive for all devices

**Comment by sajalbatra** [comment]
can you add me as assigned and hacktoberfest-accepted tag

**Comment by sajalbatra** [comment]
Made a pull request

**Comment by RamakrushnaBiswal** [comment]
solved via #47
