### ISSUE TITLE
Feat:enhance navbar design 

### ISSUE THREAD

**Issue by sanayamahajan-23** [RamakrushnaBiswal/PlayCafe#5]
### Describe the feature

i want to enhance the navbar design since it looks really basic

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ada515dd-834f-4524-a553-d79fb6dfb0ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Assigned @sanayamahajan-23

**Comment by RamakrushnaBiswal** [comment]
Hi @sanayamahajan-23 if you didn't complete it by EOD then I will assign it to @devarsheecodess

**Comment by itznayan** [comment]
please assign this issue to me i wanna make navbar like this please add level tag to this issue
Uploading Beautiful Animated Nav Bar with React & Framer Motion - YouTube - Google Chrome 2024-10-02 14-13-42 (online-video-cutter.com).mp4…

**Comment by sanayamahajan-23** [comment]
@RamakrushnaBiswal see you have assigned me this issue but when i sent the pr you closed it.

**Comment by itznayan** [comment]
i will like to work on this issue under GSSOC'24 and Hackerfest.
i want to make navbar more modern like below video.

https://github.com/user-attachments/assets/ea094e3c-745a-463b-a2b3-13c1b67aed1d

**Comment by RamakrushnaBiswal** [comment]
@itznayan it looks good and fancy typo , but its a simple project i don't think it looks for the UI

**Comment by RamakrushnaBiswal** [comment]
@sanayamahajan-23 did you work on it??
please send a PR todsy otherwise i will close the issue

**Comment by devarsheecodess** [comment]
Hey @RamakrushnaBiswal, plz dont close the issue, assign it to me. I can do this task for you

**Comment by RamakrushnaBiswal** [comment]
solved via #86
