### ISSUE TITLE
Feat: Improve Footer design

### ISSUE THREAD

**Issue by anshi05** [RamakrushnaBiswal/PlayCafe#51]
### Describe the feature

I want to improve the footer design for your website so that it looks good with the current website design. Please assign this task to me under hacktober and GSSoC extd labels. I'll make sure to complete it within a day.

### Add ScreenShots

I'm planning to revamp the footer something like this.

![image_2024-10-03_151453959](https://github.com/user-attachments/assets/491f2be5-dfbd-40e0-8fa1-a615941ded82)
  

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
No needed for now you can search another issues
