### ISSUE TITLE
Feat: Add a typing animation in the Landing Page

### ISSUE THREAD

**Issue by vishnuprasad2004** [RamakrushnaBiswal/PlayCafe#53]
### Describe the feature

Description: Adding a Typing Animation on the Landing.jsx Page similar the following Codepen

Codepen: [https://codepen.io/anon/embed/ALgzqo?default-tab=result&height=450&slug-hash=DHoup&theme-id=1#result-box](https://codepen.io/anon/embed/ALgzqo?default-tab=result&height=450&slug-hash=DHoup&theme-id=1#result-box)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/53fdfee4-39c4-46a9-bdbc-856099e002c2)

### Record

- [X] I'm a gssoc-24-extd contributor
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by vishnuprasad2004** [comment]
@RamakrushnaBiswal what do think about the feature ?

**Comment by RamakrushnaBiswal** [comment]
well @vishnuprasad2004 it look good and also add some margins in leftside
