### ISSUE TITLE
Bug:Nav bar is not responsive, its not proper in mobiles.

### ISSUE THREAD

**Issue by keerthana2-005** [RamakrushnaBiswal/PlayCafe#57]
### Describe the feature

All the fonts in the website are very big than needed and also this website isnt proper in mobiles i can cake it responsive and proper in mobiles.even all the images placed are larger than the actual sizes .i would like to work on it

### Add ScreenShots

![image](https://github.com/user-attachments/assets/cce318c5-2588-4e0c-b326-c38055769851)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
see its the desgin of the website and 
the navbar is not responvie 
you want to fix it ?
i will assign you

**Comment by keerthana2-005** [comment]
Yes I want ro work on this

**Comment by RamakrushnaBiswal** [comment]
@keerthana2-005 assigned

**Comment by keerthana2-005** [comment]
Okay

**Comment by keerthana2-005** [comment]
Thank u

**Comment by RamakrushnaBiswal** [comment]
@keerthana2-005 did you work on it please rise a PR ASAP

**Comment by keerthana2-005** [comment]
I am working on it

**Comment by RamakrushnaBiswal** [comment]
solved #224
