### ISSUE TITLE
Topic:Fix the all contributors bot

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [RamakrushnaBiswal/PlayCafe#58]
### Describe the types of topics you'd add in our Website

it not showing contributors in readme.md file

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC-24-extd contributor
- [ ] Soon, I'll complete it and create a Pull Request.

**Comment by Sapna127** [comment]
hey, I would like to work on this issue. Please assign it to me.

**Comment by RamakrushnaBiswal** [comment]
@Sapna127 assigned

**Comment by Sapna127** [comment]
@RamakrushnaBiswal I have added the workflow for fetching the contributors. Thought of achieving the end goal by doing this. 
Kindly provide your views on the same. 
I can still work on fixing the bot if you suggest.

**Comment by RamakrushnaBiswal** [comment]
@Sapna127 i am sorry to say that its my side fault 
actually i didn't follow some steps while installing the bot thats why the error will come
and if i mergerd any PR in my repo the it also counted towards hacktobor fest

you can work on different issues thank you

**Comment by RamakrushnaBiswal** [comment]
if merged any PR in the repo it considered under hacktobor-fest so don't worry about it
