### ISSUE TITLE
Feat: adding animation to landing page

### ISSUE THREAD

**Issue by itznayan** [RamakrushnaBiswal/PlayCafe#59]
### Describe the feature

adding preloader and many more animation to landing page which will improve user experience and make website more engaging. 

### Add ScreenShots

![Screenshot (133)](https://github.com/user-attachments/assets/0bca5931-e1da-4588-83ad-351c78f79601)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
solved via #60
