### ISSUE TITLE
BUG: No Responsive HomePage Image

### ISSUE THREAD

**Issue by Suhas-Koheda** [RamakrushnaBiswal/PlayCafe#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The background image and texts aren't responsive 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by Suhas-Koheda** [comment]
@RamakrushnaBiswal  can you please look into it

**Comment by RamakrushnaBiswal** [comment]
Assigned @Suhas-Koheda

**Comment by RamakrushnaBiswal** [comment]
fixed via #47
