### ISSUE TITLE
BUG: UI Improvement in the feedback form frontend

### ISSUE THREAD

**Issue by vishnuprasad2004** [RamakrushnaBiswal/PlayCafe#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

We can improve the way the feedback form looks with simple tailwind and no extra library, so it's not a bug but an improvement.
It would reduce the space the feedback form takes and make it look more professional.

![image](https://github.com/user-attachments/assets/9c61732e-597e-4418-a83e-691291a28f51)

 Please assign it to me. :)
 
 If any other field is required, I can add that as well.
* hacktoberfest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
assigned @vishnuprasad2004 
also you can create multiple issues at a time

**Comment by RamakrushnaBiswal** [comment]
solved #75
