### ISSUE TITLE
Feat: Enhance Hamburger Menu to Toggle to 'X' on Mobile

### ISSUE THREAD

**Issue by MutiatBash** [RamakrushnaBiswal/PlayCafe#62]
### Describe the feature

Currently, the hamburger menu icon on mobile screens does not change when the navigation menu drops down. This can lead to confusion for users, as they may not realize that the menu is open or that they can close it.

When the hamburger menu icon is clicked and the navigation menu is expanded, the hamburger icon should transition to an "X", indicating that users can click it again to close the menu.

### Add ScreenShots
![IMG_7246](https://github.com/user-attachments/assets/7c62e636-6e42-490c-a841-4f3048231888)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
assigned @MutiatBash

**Comment by RamakrushnaBiswal** [comment]
Solved via #83
