### ISSUE TITLE
 Create a System for Dynamically Displaying Events in the Café Website

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#63]
### Describe the feature

Description:
Really great working on this repo. Want to contribute More. @RamakrushnaBiswal! Currently, the Events section on the café website  is purely frontend-based and static. This issue proposes the creation of a system to dynamically manage and display events based on data from a database.

Proposed Solution:

Backend Setup for Events:
Implement a backend system (Node.js/Express) that fetches event data from a database (e.g., MongoDB, SQL).

Dynamic Event Display:
Replace the static events display with a dynamic one, where only upcoming events are shown.
Retrieve event data (e.g., title, description, date/time) from the database and display it dynamically on the frontend.

Event Expiry Management:
Automatically delete past events from the database once the event time has passed, ensuring that only active/upcoming events are displayed.

Benefits:
This will ensure that the Events section is always up-to-date, displaying only active and upcoming events.
Reduces the need for manual updates of the frontend, making event management more efficient.
Improves the overall functionality and responsiveness of the café website.

### Add ScreenShots

https://github.com/user-attachments/assets/c21848b9-7862-4b71-ac44-30aa16f6f2d2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad go for it 🚀

**Comment by RamakrushnaBiswal** [comment]
what i think ,
1st we need to create a admin panel for that and then we can add here all the stuff like events games and all 
also use simple kinde auth for that

**Comment by samar12-rad** [comment]
I understand your point @RamakrushnaBiswal . We first need to create a system for admins to create new events in the website. We need both frontend and backend of admin panels. Can i create an issue to create the admin page and its backend first, then i will integrate the creating the events in the website ?
