### ISSUE TITLE
BUG: There is a cookie storage for the Name input field in the form section. 

### ISSUE THREAD

**Issue by maitri-vv** [RamakrushnaBiswal/PlayCafe#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

For enabling better privacy of user's data there needs to be autocomplete off in the input fields of the form section. It should prevent the cookie storage and protects the data by not being exposed to other users when entering in the input field.
![image](https://github.com/user-attachments/assets/b4a81c08-363e-4a13-8f97-f7ca14cde7bf)

Assign me under Hacktoberfest 2024 label :)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
Not needed for now 
you can work on other issues
