### ISSUE TITLE
Feat: Back to top button

### ISSUE THREAD

**Issue by maitri-vv** [RamakrushnaBiswal/PlayCafe#66]
### Describe the feature

Since its long site scrolling till bottom and and again to top is hard. Adding bottom to top button will help

### Add ScreenShots

Button-Icon for Top up button

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
assigned @maitri-vv 
match the button with the UI

**Comment by RamakrushnaBiswal** [comment]
solved #84
