### ISSUE TITLE
BUG: Scrollbar Visibility

### ISSUE THREAD

**Issue by MishraTanishq619** [RamakrushnaBiswal/PlayCafe#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description:
There is some bug or lower user experience with using scrollbar.

Current behaviour: Scroll bar Thumb is visible only if we hover on the Thumb and not visible if we hover on the Track. This is making difficult to locate the scrollbar on the scrollbar-track.

Expected Change:  Thumb should be visible even when we hover on the scrollbar track.

![Screenshot from 2024-10-04 10-40-10](https://github.com/user-attachments/assets/533d4a73-0981-4faa-9b95-974864f4fadb)
![Screenshot from 2024-10-04 10-39-44](https://github.com/user-attachments/assets/183e3d11-3057-4c54-9805-20efba708763)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
not need for now @MishraTanishq619
