### ISSUE TITLE
want to update .gitignore file

### ISSUE THREAD

**Issue by ChandraST12** [RamakrushnaBiswal/PlayCafe#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

It appears that both the .env.sample and .env files have been pushed to the repository. The .env file contains sensitive environment variables such as API keys, credentials, and other private information. This poses a significant security risk, as these secrets are now publicly accessible

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
assigned @ChandraST12

**Comment by RamakrushnaBiswal** [comment]
solved
