### ISSUE TITLE
BUG: Text inside testimonial cards is cut off on different screen sizes and responsive landing page

### ISSUE THREAD

**Issue by iamsaura8h** [RamakrushnaBiswal/PlayCafe#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description: 
The text inside the testimonial cards is not adjusting properly based on screen size. On smaller screens, the text is cut off, making it difficult for users to read the entire testimonial content. This issue affects the readability and overall user experience on mobile and tablet devices.

![image](https://github.com/user-attachments/assets/2ad622d0-7b89-4758-ab5e-7ad33a178f12)

## Expected Behavior: 
The text inside the testimonial cards should adjust responsively based on the screen size, either by resizing the text or wrapping it within the card. On smaller screens, the entire text should be visible without being cut off.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
hi @iamsaura8h thank you for rising the issue
for me its looks good in my laptop 
if you want you can make the landing page responsive

**Comment by iamsaura8h** [comment]
Alright i am on it just assign me this issue and give gssoc and hacktoberfest label it would be very helpful

**Comment by RamakrushnaBiswal** [comment]
go for it

**Comment by RamakrushnaBiswal** [comment]
#6

**Comment by RamakrushnaBiswal** [comment]
solved #47
