### ISSUE TITLE
BUG:Reservation Buttons not working and Calender is not dynamic

### ISSUE THREAD

**Issue by Pratik2401** [RamakrushnaBiswal/PlayCafe#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

1.Register Event Btns not working reserve now not working...
2.Calender Should show the available spots in green and other in red
![image](https://github.com/user-attachments/assets/0389dd64-2bd9-4e01-904a-715ce04893b5)
![image](https://github.com/user-attachments/assets/1440f07b-d650-410e-bab5-8bb96d4913c6)
![image](https://github.com/user-attachments/assets/e2edc18e-8706-41e2-8bbe-14126791de67)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by Pratik2401** [comment]
Can you asssign me this under hacktoberfest 2024

**Comment by RamakrushnaBiswal** [comment]
someone working on it #63
