### ISSUE TITLE
Feat:  Implement Logger for Error Handling in Backend

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#72]
### Describe the feature

Description: This is from the pr #65 @RamakrushnaBiswal .
Currently, the backend of the café website is handling errors using console.log and console.error, which is not ideal for production environments. To follow industry standards and improve error handling, we should incorporate a logging library like Winston or Morgan.

Proposed Solution:

Incorporate a Logger Library:
Implement a logging library such as Winston or Morgan in the backend.
Configure the logger to handle different levels of logs (e.g., info, warn, error), and log errors more effectively.

Replace console.log and console.error:
Identify and replace all instances of console.log and console.error with the appropriate logger methods (e.g., logger.info(), logger.error()).

Enhance Error Tracking:
Ensure that logs capture relevant metadata (like timestamps, request information, etc.) for better debugging and monitoring.
Optionally, configure logs to be saved in files or external services (like Loggly, Sentry, etc.) for better error monitoring.

Benefits:
Improves error tracking and handling in the backend.
Provides detailed logs for debugging and monitoring, which is essential for production.
Helps in maintaining logs over time, which can assist in identifying issues more easily.

@RamakrushnaBiswal , pls assign me this

### Add ScreenShots

![image](https://github.com/user-attachments/assets/96080fb6-94c8-4c99-890c-7a4865aa3361)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
assigned @samar12-rad

**Comment by RamakrushnaBiswal** [comment]
solved via #89
