### ISSUE TITLE
Feat: Display global messages as feedback in response to user operations using antd 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [RamakrushnaBiswal/PlayCafe#76]
### Describe the feature

ref:- https://ant.design/components/message

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f7cdcce7-30ea-41ee-949f-8628a66db2c7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-extd contributor
- [ ] I want to work on this issue

**Comment by 17arindam** [comment]
@RamakrushnaBiswal assign me this issue

**Comment by RamakrushnaBiswal** [comment]
@17arindam assigned

**Comment by RamakrushnaBiswal** [comment]
Solved via #94
