### ISSUE TITLE
BUG: Inconsistent margins and paddings

### ISSUE THREAD

**Issue by tejasbenibagde** [RamakrushnaBiswal/PlayCafe#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Inconsistent Margins and Padding Across Components

After reviewing the site, I noticed inconsistencies in the margins and padding across different components, which affect the overall layout and user experience.

#### Example 1:
![Example 1](https://github.com/user-attachments/assets/de719871-c034-4e17-b22d-08c0b226dd97)

#### Example 2:
![Example 2](https://github.com/user-attachments/assets/bf85f985-9268-4e79-abbb-d8ab012d0d57)

I've attached screenshots for better visualization of the issue. 

**Proposal**: I would like to work on this issue to standardize the margins and padding for all components, ensuring consistency throughout the site.

Kindly assign the appropriate labels, as I am a contributor for GSSOC 2024.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

**Comment by RamakrushnaBiswal** [comment]
Its not a big issue you can work upon another issues

**Comment by tejasbenibagde** [comment]
@RamakrushnaBiswal  what is a problem with you? you even closed my issue now? are you really expecting every issue should be of high level difficulty?

**Comment by RamakrushnaBiswal** [comment]
@tejasbenibagde for me the margin and padding is looks good

**Comment by tejasbenibagde** [comment]
@RamakrushnaBiswal  how can you say this without even looking at my updated code ? did you ever compared it?

**Comment by tejasbenibagde** [comment]
@RamakrushnaBiswal  sorry but I'm reporting you to the GSSOC community.

**Comment by RamakrushnaBiswal** [comment]
Ok go for no issues @tejasbenibagde

**Comment by RamakrushnaBiswal** [comment]
> @RamakrushnaBiswal how can you say this without even looking at my updated code ? did you ever compared it?

Well I looked into that you change too many files

**Comment by tejasbenibagde** [comment]
@RamakrushnaBiswal  You are correct I changed too many files cause I worked for hours doing that just for you to ignore everything in seconds.

**Comment by RamakrushnaBiswal** [comment]
> @RamakrushnaBiswal You are correct I changed too many files cause I worked for hours doing that just for you to ignore everything in seconds.

I am really sorry about that you should follow the rules 
1. Create a issue 
2. Wait for project admin assign 
3. Then go for work 

I think it's your 1st time in open source

**Comment by tejasbenibagde** [comment]
It is not my first time doing it but I understand your point of view now. Sorry I went hyper all of a sudden.

**Comment by tejasbenibagde** [comment]
@RamakrushnaBiswal  While working on the project, I noticed several optimization and modularization issues that are impacting the site's performance. I believe I can address these issues to improve the overall speed and efficiency of the application.

Would you like me to create a new issue for this? If so, could you please assign it to me? I want to mention that this may involve changes to multiple files, but I’ll ensure everything is well-documented.
