### ISSUE TITLE
Feat: Add user Log In and Sing up apil's for Backend 

### ISSUE THREAD

**Issue by shahbaz36** [RamakrushnaBiswal/PlayCafe#90]
### Describe the feature

Your frontend contains a Login button without any functionality, i can help to establish user authentication and authorization in the following way: 

1. I will create a Robust user schema with strong password management using mongoose
2. Addition of JSON web token for authentication. Every time user singin or singup we will send token back to user.
3. Based on the schema user Singup will be implemented 
4. After Singup api, i will implement Singin apis for user to log into the application. 
5. Along with this there will be another Protect middleware which can be chained with other middleware to protect routes from unauthorized access. This middleware will make the user document available on request body.
6. For authorization we can also add a restrictTo middleware which will restrict the routes to specific users with this only admin routes can be protected.

### Add ScreenShots

![User Schema](https://github.com/user-attachments/assets/f07a45ac-b108-4b9d-97c6-6ccb92df8468)
![Routes for singin and singup](https://github.com/user-attachments/assets/506b4f76-08df-4bb0-9091-feb04295078d)
![Postman: singup api](https://github.com/user-attachments/assets/dd04867a-7b81-4c76-9a43-b135e7ddc277)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@shahbaz36 actually we use kinde auth can you comfortable with that ?
