### ISSUE TITLE
Project Proposal:  Add events in Events section

### ISSUE THREAD

**Issue by Mohitranag18** [RamakrushnaBiswal/PlayCafe#93]
### Overview

Add events like jaming, open mic, dancing, any games compition in the Events section. add information about those events like upcoming events and previous events we conducted, add date, photos and discription about those events.
for upcoming events there should be a register now button through which customers can rester there presence in that event.

### Key Features

2 sections, 1st is previous events and 2nd is upcoming events.
Register now button for upcoming events.
Interactive UI
Events cards Like open mic, dancing, talent showcase

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this project proposal
- [X] It is not duplicate

**Comment by Mohitranag18** [comment]
please assign this issue to me i will make full event section, with beautiful UI and interractive elements.

**Comment by RamakrushnaBiswal** [comment]
@Mohitranag18 I think someone working on that issue 
We will implement a new section live music if you want you can work upon that

**Comment by RamakrushnaBiswal** [comment]
#63 duplicate issue
