### ISSUE TITLE
Display Profile Page for Users

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#95]
### Describe the feature

Description:
After the implementation of users login in the website, there is need of, creating the database for them and  showing their profiles in the website .Implement a feature that displays a profile page exclusively for users on the café website. This page will act as a user dashboard, showing personal information and activities such as past reservations, events attended, and feedback submitted.

Features:

User Profile Display:

Show personal information like:
Name
Email
Contact number
List of past café reservations or event registrations.

Backend Requirements:
Create API routes to fetch user data from the database, including:
Personal information
Reservation history

Frontend Requirements:
Design and implement a user-friendly UI to display the profile page.
Ensure responsive design for mobile and desktop views.
Add navigation in the header/menu to the profile page for logged-in users.
@RamakrushnaBiswal 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c66c7c72-a310-4ecf-8cbe-6aa62f31f092)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad in kinde auth can we implement that ?
or we need to create login and sign up pages ??

**Comment by samar12-rad** [comment]
Kinde auth handles login and sign up pages

**Comment by samar12-rad** [comment]
We can't incorporate profile section, as kinde auth only stores email and password and returns verified res.json

**Comment by samar12-rad** [comment]
Also currently there is no way to know you logged in as that button is not dynamic, logic routing with layout is supposed to be done for that .
