### ISSUE TITLE
Feat: Back to top button

### ISSUE THREAD

**Issue by shreyad2806** [RamakrushnaBiswal/PlayCafe#96]
### Describe the feature

The "Back to Top" button enhances user experience, particularly on content-rich sites, by simplifying navigation. By integrating this feature effectively, websites can ensure users have a more seamless and enjoyable browsing experience.
Please give level2

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0578c33a-6e14-4b9d-8948-a9327866644f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
#66

**Comment by RamakrushnaBiswal** [comment]
@shreyad2806 no its not assigned its  a duplicate issue #66
