### ISSUE TITLE
Feat: Add Today's Special in Menu page

### ISSUE THREAD

**Issue by Mohitranag18** [RamakrushnaBiswal/PlayCafe#97]
### Describe the feature

The "Today's Special" section will feature three categories: Special Coffee, Drinks, and Food, each highlighting a unique item of the day. This organization allows customers to easily explore specific offerings, whether they're interested in a special brew, a refreshing beverage, or a delicious meal. It adds variety, enhances user experience, and encourages repeat visits by showcasing rotating specials in each category daily.

### Add ScreenShots

![Screenshot (182)](https://github.com/user-attachments/assets/492a1106-d5fb-4bda-a9fe-87fe8c684e77)

i will add a todays special section below menu or if not look right we can shift that top of menu.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by Mohitranag18** [comment]
please assign this issue to me

**Comment by RamakrushnaBiswal** [comment]
@Mohitranag18 yh you can a section below the menu book then do that
assigned

**Comment by RamakrushnaBiswal** [comment]
solved #128
