### ISSUE TITLE
Redesign Events and Programs Page with Hero Section

### ISSUE THREAD

**Issue by samar12-rad** [RamakrushnaBiswal/PlayCafe#98]
### Describe the feature

The current Events and Programs page UI needs a complete redesign to enhance user engagement and create a visually appealing layout. The updated design will include a hero section at the top and improved presentation of events and programs, making it more intuitive and engaging for users.

Key Features:

Hero Section:
Add a captivating hero section at the top of the page with a background image related to café events or programs.
Include a short headline about upcoming events and a call-to-action button like "View Upcoming Events."

Event Display:
Redesign how events are listed, focusing on modern design principles.

Each event/program should display:
Event name
Description
Date and time
Event type (e.g., board games, live music)
CTA button for booking/registering

Improved Typography and Spacing:
Update fonts, spacing, and colors to make the content easier to read and aesthetically pleasing.

Prepare the design for dynamic updates, so future events can be fetched from the database and shown automatically. @RamakrushnaBiswal , pls assign me this issue 

### Add ScreenShots

![image_2024-10-06_091927055](https://github.com/user-attachments/assets/2c381294-27ce-4ad8-a01f-ce0bf6a28d8f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad assigned

**Comment by RamakrushnaBiswal** [comment]
solved via #120
